import { indiceIdioma, TRADUCOES, type Chave } from '../i18n'
// Catálogo de emojis do seletor (src/components/common/EmojiPicker.tsx).
//
// As categorias e a ordem seguem o teclado de emoji do iPhone. O DESENHO de cada emoji vem
// da fonte do sistema — em iPhone/Mac já é a arte da Apple, no Windows/Android é a da própria
// plataforma. Servir a arte da Apple em qualquer aparelho exigiria baixar as imagens de uma
// CDN externa, coisa que este app não faz.
//
// `k` são as palavras-chave da busca, nos três idiomas, com sinônimos comuns. A busca
// normaliza acentos dos dois lados (ver `searchEmojis`), então "coracao" acha "coração".
//
// A BUSCA OLHA OS TRÊS AO MESMO TEMPO, e não só o idioma da tela. Quem pôs o CRM em inglês
// e digita "coração" acha o coração; quem está em português e digita "heart" também.
// Procurar é tentar lembrar — achar demais ajuda, achar de menos irrita. De quebra, o
// índice deixa de depender do idioma ativo e não precisa ser refeito a cada troca.

export interface EmojiEntry {
  /** O caractere em si. */
  e: string
  /**
   * Palavras-chave da busca, separadas por espaço, uma lista por idioma:
   * [pt, es, en]. Mesma forma do catálogo — e pelo mesmo motivo, já que aqui
   * também uma tupla incompleta não compila.
   */
  k: [string, string, string]
}

export interface EmojiCategory {
  id: string
  /** Rótulo exibido acima da grade. */
  /** Chave do catálogo — o rótulo é traduzido em quem desenha o seletor. */
  label: Chave
  /** Emoji usado como ícone da aba (mesma ideia das abas do iPhone). */
  icon: string
  items: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'emoji.catSmileys',
    icon: '😀',
    items: [
      { e: '😀', k: ['sorriso feliz cara alegre', 'sonrisa feliz cara alegre', 'smile happy face grin'] },
      { e: '😃', k: ['sorriso feliz alegre boca aberta', 'sonrisa feliz alegre boca abierta', 'smile happy open mouth grin'] },
      { e: '😄', k: ['sorriso feliz alegre olhos', 'sonrisa feliz alegre ojos', 'smile happy eyes laughing'] },
      { e: '😁', k: ['sorriso radiante feliz dentes', 'sonrisa radiante feliz dientes', 'beaming smile happy teeth grin'] },
      { e: '😆', k: ['risada gargalhada feliz', 'risa carcajada feliz', 'laugh squinting happy lol'] },
      { e: '😅', k: ['risada suor alivio nervoso', 'risa sudor alivio nervioso', 'laugh sweat relief nervous'] },
      { e: '🤣', k: ['risada rolando chao gargalhada rindo', 'risa rodando suelo carcajada riendo', 'rofl rolling floor laughing'] },
      { e: '😂', k: ['risada chorando de rir lagrima gargalhada', 'risa llorando de risa lagrima carcajada', 'tears of joy laughing crying lol'] },
      { e: '🙂', k: ['sorriso leve simpatico', 'sonrisa leve simpatico', 'slight smile friendly'] },
      { e: '🙃', k: ['cabeca para baixo ironia sarcasmo', 'cabeza abajo ironia sarcasmo', 'upside down irony sarcasm silly'] },
      { e: '😉', k: ['piscada flerte brincadeira', 'guino coqueteo broma', 'wink flirt joke'] },
      { e: '😊', k: ['sorriso timido feliz corado', 'sonrisa timida feliz sonrojado', 'smiling blush shy happy'] },
      { e: '😇', k: ['anjo santo auréola inocente', 'angel santo aureola inocente', 'angel halo innocent saint'] },
      { e: '🥰', k: ['apaixonado amor coracoes carinho', 'enamorado amor corazones carino', 'in love hearts smiling adore'] },
      { e: '😍', k: ['apaixonado olhos de coracao amor', 'enamorado ojos de corazon amor', 'heart eyes love adore'] },
      { e: '🤩', k: ['estrelas deslumbrado uau incrivel', 'estrellas deslumbrado guau increible', 'star struck amazed wow awesome'] },
      { e: '😘', k: ['beijo mandando beijo amor', 'beso mandando beso amor', 'blowing kiss love'] },
      { e: '😗', k: ['beijo bico', 'beso morritos', 'kissing pucker'] },
      { e: '😚', k: ['beijo olhos fechados', 'beso ojos cerrados', 'kissing closed eyes'] },
      { e: '😙', k: ['beijo sorriso', 'beso sonrisa', 'kissing smiling'] },
      { e: '😋', k: ['delicia lambendo gostoso saboroso', 'delicia relamiendo rico sabroso', 'yum delicious tasty savoring'] },
      { e: '😛', k: ['lingua brincadeira', 'lengua broma', 'tongue out playful'] },
      { e: '😜', k: ['lingua piscada brincalhao', 'lengua guino travieso', 'tongue wink playful'] },
      { e: '🤪', k: ['doido maluco louco', 'chalado loco zumbado', 'zany crazy goofy wild'] },
      { e: '😝', k: ['lingua olhos fechados brincadeira', 'lengua ojos cerrados broma', 'tongue closed eyes squinting'] },
      { e: '🤑', k: ['dinheiro cifrao rico ganancia', 'dinero signo dolar rico codicia', 'money dollar rich greedy'] },
      { e: '🤗', k: ['abraco acolhimento carinho', 'abrazo acogida carino', 'hug hugging warm'] },
      { e: '🤭', k: ['ops boca tapada risadinha', 'ups boca tapada risita', 'oops hand over mouth giggle'] },
      { e: '🤫', k: ['silencio shh segredo', 'silencio shh secreto', 'shush quiet secret'] },
      { e: '🤔', k: ['pensando duvida hmm reflexao', 'pensando duda hmm reflexion', 'thinking hmm wondering'] },
      { e: '🤐', k: ['boca fechada ziper calado', 'boca cerrada cremallera callado', 'zipper mouth quiet sealed'] },
      { e: '🤨', k: ['sobrancelha desconfiado duvida', 'ceja desconfiado duda', 'raised eyebrow skeptical suspicious'] },
      { e: '😐', k: ['neutro sem expressao', 'neutral sin expresion', 'neutral expressionless blank'] },
      { e: '😑', k: ['sem expressao entediado', 'sin expresion aburrido', 'expressionless bored blank'] },
      { e: '😶', k: ['sem boca mudo calado', 'sin boca mudo callado', 'no mouth speechless silent'] },
      { e: '😏', k: ['sorriso malicioso safado convencido', 'sonrisa picara pillo creido', 'smirk sly smug'] },
      { e: '😒', k: ['chateado sem gracao contrariado', 'molesto sin gracia contrariado', 'unamused annoyed meh'] },
      { e: '🙄', k: ['revirando os olhos tedio ironia', 'poniendo los ojos en blanco tedio ironia', 'eye roll bored sarcasm'] },
      { e: '😬', k: ['careta constrangido nervoso', 'mueca incomodo nervioso', 'grimace awkward nervous'] },
      { e: '🤥', k: ['mentira nariz pinoquio', 'mentira nariz pinocho', 'lying nose pinocchio'] },
      { e: '😌', k: ['aliviado calmo tranquilo', 'aliviado tranquilo calmado', 'relieved calm content'] },
      { e: '😔', k: ['triste pensativo desanimado', 'triste pensativo desanimado', 'sad pensive dejected'] },
      { e: '😪', k: ['sono cansado dormindo', 'sueno cansado durmiendo', 'sleepy tired drowsy'] },
      { e: '🤤', k: ['babando desejo fome', 'babeando deseo hambre', 'drooling craving hungry'] },
      { e: '😴', k: ['dormindo sono zzz', 'durmiendo sueno zzz', 'sleeping snore zzz'] },
      { e: '😷', k: ['mascara doente gripe', 'mascarilla enfermo gripe', 'mask sick flu'] },
      { e: '🤒', k: ['doente febre termometro', 'enfermo fiebre termometro', 'sick fever thermometer'] },
      { e: '🤕', k: ['machucado curativo ferido', 'herido venda lastimado', 'injured bandage hurt'] },
      { e: '🤢', k: ['enjoado nojo verde', 'mareado asco verde', 'nauseated sick green disgust'] },
      { e: '🤮', k: ['vomitando enjoo nojo', 'vomitando nauseas asco', 'vomiting puke sick'] },
      { e: '🤧', k: ['espirro resfriado gripe', 'estornudo resfriado gripe', 'sneeze cold flu'] },
      { e: '🥵', k: ['calor quente suando', 'calor sofocado sudando', 'hot overheated sweating'] },
      { e: '🥶', k: ['frio congelando gelo', 'frio congelado hielo', 'cold freezing ice'] },
      { e: '🥴', k: ['tonto bebado zonzo', 'mareado borracho aturdido', 'woozy drunk dizzy'] },
      { e: '😵', k: ['tonto atordoado desmaio', 'mareado aturdido desmayo', 'dizzy knocked out faint'] },
      { e: '🤯', k: ['explodindo mente chocado uau', 'cabeza explotando conmocionado guau', 'mind blown exploding head shocked'] },
      { e: '🤠', k: ['cowboy chapeu caubói', 'vaquero sombrero cowboy', 'cowboy hat yeehaw'] },
      { e: '🥳', k: ['festa comemoracao aniversario', 'fiesta celebracion cumpleanos', 'party celebration birthday'] },
      { e: '😎', k: ['oculos escuros estiloso legal', 'gafas de sol con estilo guay', 'sunglasses cool stylish'] },
      { e: '🤓', k: ['nerd geek estudioso oculos', 'empollon friki estudioso gafas', 'nerd geek glasses studious'] },
      { e: '🧐', k: ['monoculo analisando curioso', 'monoculo analizando curioso', 'monocle inspecting curious'] },
      { e: '😕', k: ['confuso incerto', 'confundido inseguro', 'confused unsure'] },
      { e: '😟', k: ['preocupado aflito', 'preocupado afligido', 'worried anxious'] },
      { e: '🙁', k: ['triste leve descontente', 'triste leve descontento', 'slightly sad frowning'] },
      { e: '😮', k: ['surpreso boca aberta uau', 'sorprendido boca abierta guau', 'surprised open mouth wow'] },
      { e: '😯', k: ['surpreso espantado', 'sorprendido asombrado', 'hushed surprised astonished'] },
      { e: '😲', k: ['chocado assombrado surpresa', 'conmocionado asombrado sorpresa', 'astonished shocked gasp'] },
      { e: '😳', k: ['envergonhado corado surpreso', 'avergonzado sonrojado sorprendido', 'flushed embarrassed blushing'] },
      { e: '🥺', k: ['implorando carinha pidao fofo', 'suplicando carita ojitos tierno', 'pleading puppy eyes cute beg'] },
      { e: '😦', k: ['assustado boca aberta', 'asustado boca abierta', 'frowning open mouth scared'] },
      { e: '😧', k: ['angustiado aflito', 'angustiado afligido', 'anguished distressed'] },
      { e: '😨', k: ['medo assustado', 'miedo asustado', 'fearful scared afraid'] },
      { e: '😰', k: ['ansioso suor medo', 'ansioso sudor miedo', 'anxious sweat nervous'] },
      { e: '😥', k: ['triste aliviado decepcionado', 'triste aliviado decepcionado', 'sad relieved disappointed'] },
      { e: '😢', k: ['chorando triste lagrima', 'llorando triste lagrima', 'crying sad tear'] },
      { e: '😭', k: ['chorando muito triste soluco', 'llorando mucho triste sollozo', 'sobbing bawling crying loud'] },
      { e: '😱', k: ['grito medo panico susto', 'grito miedo panico susto', 'scream fear panic horror'] },
      { e: '😖', k: ['confuso frustrado', 'confundido frustrado', 'confounded frustrated'] },
      { e: '😣', k: ['perseverando esforco dor', 'perseverando esfuerzo dolor', 'persevering struggling effort'] },
      { e: '😞', k: ['decepcionado triste', 'decepcionado triste', 'disappointed sad'] },
      { e: '😓', k: ['suando triste cansado', 'sudando triste cansado', 'sad sweat downcast tired'] },
      { e: '😩', k: ['cansado exausto chateado', 'cansado agotado molesto', 'weary tired upset'] },
      { e: '😫', k: ['exausto cansado desesperado', 'agotado cansado desesperado', 'tired exhausted fed up'] },
      { e: '🥱', k: ['bocejo sono tedio', 'bostezo sueno aburrimiento', 'yawn sleepy bored'] },
      { e: '😤', k: ['bufando raiva orgulho', 'resoplando rabia orgullo', 'huffing triumph steam pride'] },
      { e: '😡', k: ['raiva bravo furioso vermelho', 'rabia enfadado furioso rojo', 'rage angry furious red'] },
      { e: '😠', k: ['bravo irritado raiva', 'enfadado irritado rabia', 'angry mad annoyed'] },
      { e: '🤬', k: ['xingando palavrao raiva', 'insultando palabrota rabia', 'cursing swearing angry'] },
      { e: '😈', k: ['diabo travesso safado', 'diablo travieso picaro', 'devil mischief naughty imp'] },
      { e: '👿', k: ['diabo bravo raiva', 'diablo enfadado rabia', 'angry devil imp rage'] },
      { e: '💀', k: ['caveira morte cranio', 'calavera muerte craneo', 'skull death dead'] },
      { e: '💩', k: ['coco merda bosta', 'caca mierda popo', 'poop crap turd'] },
      { e: '🤡', k: ['palhaco circo', 'payaso circo', 'clown circus'] },
      { e: '👻', k: ['fantasma assombracao halloween', 'fantasma aparicion halloween', 'ghost boo halloween'] },
      { e: '👽', k: ['alien et extraterrestre', 'alien extraterrestre marciano', 'alien extraterrestrial ufo'] },
      { e: '🤖', k: ['robo bot inteligencia artificial', 'robot bot inteligencia artificial', 'robot bot artificial intelligence'] },
      { e: '🎃', k: ['abobora halloween', 'calabaza halloween', 'pumpkin jack o lantern halloween'] },
      { e: '😺', k: ['gato sorrindo', 'gato sonriendo', 'grinning cat smile'] },
      { e: '😻', k: ['gato apaixonado coracao', 'gato enamorado corazon', 'heart eyes cat love'] },
      { e: '🙈', k: ['macaco nao vejo vergonha', 'mono no veo verguenza', 'see no evil monkey shy'] },
      { e: '🙉', k: ['macaco nao ouco', 'mono no oigo', 'hear no evil monkey'] },
      { e: '🙊', k: ['macaco nao falo segredo', 'mono no hablo secreto', 'speak no evil monkey secret'] },
      { e: '❤️', k: ['coracao amor vermelho', 'corazon amor rojo', 'heart love red'] },
      { e: '🧡', k: ['coracao laranja amor', 'corazon naranja amor', 'orange heart love'] },
      { e: '💛', k: ['coracao amarelo amor amizade', 'corazon amarillo amor amistad', 'yellow heart love friendship'] },
      { e: '💚', k: ['coracao verde amor', 'corazon verde amor', 'green heart love'] },
      { e: '💙', k: ['coracao azul amor', 'corazon azul amor', 'blue heart love'] },
      { e: '💜', k: ['coracao roxo amor', 'corazon morado amor', 'purple heart love'] },
      { e: '🖤', k: ['coracao preto', 'corazon negro', 'black heart'] },
      { e: '🤍', k: ['coracao branco', 'corazon blanco', 'white heart'] },
      { e: '🤎', k: ['coracao marrom', 'corazon marron', 'brown heart'] },
      { e: '💔', k: ['coracao partido termino tristeza', 'corazon roto ruptura tristeza', 'broken heart breakup sad'] },
      { e: '❣️', k: ['coracao exclamacao amor', 'corazon exclamacion amor', 'heart exclamation love'] },
      { e: '💕', k: ['dois coracoes amor', 'dos corazones amor', 'two hearts love'] },
      { e: '💞', k: ['coracoes girando amor', 'corazones girando amor', 'revolving hearts love'] },
      { e: '💓', k: ['coracao batendo amor', 'corazon latiendo amor', 'beating heart love'] },
      { e: '💗', k: ['coracao crescendo amor', 'corazon creciendo amor', 'growing heart love'] },
      { e: '💖', k: ['coracao brilhando amor', 'corazon brillante amor', 'sparkling heart love'] },
      { e: '💘', k: ['coracao flecha cupido paixao', 'corazon flecha cupido pasion', 'heart arrow cupid love'] },
      { e: '💝', k: ['coracao presente laco', 'corazon regalo lazo', 'heart gift ribbon'] },
      { e: '💯', k: ['cem nota maxima perfeito', 'cien nota maxima perfecto', 'hundred perfect score full marks'] },
      { e: '💢', k: ['raiva irritacao', 'rabia enfado irritacion', 'anger symbol mad irritation'] },
      { e: '💥', k: ['explosao boom', 'explosion boom', 'explosion boom collision'] },
      { e: '💫', k: ['tontura estrelas', 'mareo estrellas', 'dizzy stars'] },
      { e: '💦', k: ['gotas suor agua', 'gotas sudor agua', 'sweat drops water splash'] },
      { e: '💨', k: ['vento correndo fumaca', 'viento corriendo humo', 'dash wind running smoke'] },
      { e: '👋', k: ['tchau oi aceno mao', 'adios hola saludo mano', 'wave hello bye hand'] },
      { e: '🤚', k: ['mao levantada', 'mano levantada', 'raised back of hand'] },
      { e: '✋', k: ['mao parada stop', 'mano alto stop', 'raised hand stop'] },
      { e: '🖐️', k: ['mao dedos abertos', 'mano dedos abiertos', 'hand splayed fingers'] },
      { e: '👌', k: ['ok joia certo perfeito', 'ok bien correcto perfecto', 'ok hand perfect good'] },
      { e: '🤌', k: ['mao italiana gesto', 'mano italiana gesto', 'pinched fingers italian gesture'] },
      { e: '🤏', k: ['pouco pequeno pitada', 'poco pequeno pizca', 'pinch small tiny bit'] },
      { e: '✌️', k: ['paz vitoria dois dedos', 'paz victoria dos dedos', 'peace victory two fingers'] },
      { e: '🤞', k: ['dedos cruzados sorte torcendo', 'dedos cruzados suerte', 'fingers crossed luck hope'] },
      { e: '🤟', k: ['amor rock mao', 'amor rock mano', 'love you gesture rock hand'] },
      { e: '🤘', k: ['rock chifrinho metal', 'rock cuernos metal', 'horns rock metal'] },
      { e: '🤙', k: ['me liga shaka', 'llamame shaka', 'call me hand shaka'] },
      { e: '👈', k: ['apontando esquerda', 'senalando izquierda', 'pointing left'] },
      { e: '👉', k: ['apontando direita', 'senalando derecha', 'pointing right'] },
      { e: '👆', k: ['apontando cima', 'senalando arriba', 'pointing up'] },
      { e: '👇', k: ['apontando baixo', 'senalando abajo', 'pointing down'] },
      { e: '☝️', k: ['dedo indicador cima atencao', 'dedo indice arriba atencion', 'index finger up attention'] },
      { e: '👍', k: ['joia positivo curtir like legal', 'pulgar arriba bien me gusta guay', 'thumbs up like good yes'] },
      { e: '👎', k: ['negativo nao gostei deslike', 'pulgar abajo no me gusta', 'thumbs down dislike no'] },
      { e: '✊', k: ['punho forca luta', 'puno fuerza lucha', 'fist power solidarity'] },
      { e: '👊', k: ['soco punho toca aqui', 'puno choca esos cinco', 'fist bump punch'] },
      { e: '🤛', k: ['punho esquerda', 'puno izquierda', 'left fist bump'] },
      { e: '🤜', k: ['punho direita', 'puno derecha', 'right fist bump'] },
      { e: '👏', k: ['palmas aplauso parabens', 'palmas aplauso felicidades', 'clap applause bravo'] },
      { e: '🙌', k: ['maos ao alto comemorar aleluia', 'manos arriba celebrar aleluya', 'raising hands celebrate hooray'] },
      { e: '👐', k: ['maos abertas abraco', 'manos abiertas abrazo', 'open hands hug'] },
      { e: '🤲', k: ['maos juntas pedido oracao', 'manos juntas peticion oracion', 'palms up together plea prayer'] },
      { e: '🤝', k: ['aperto de mao acordo negocio parceria', 'apreton de manos acuerdo negocio', 'handshake deal agreement partnership'] },
      { e: '🙏', k: ['oracao obrigado por favor reza', 'oracion gracias por favor rezo', 'pray thanks please namaste'] },
      { e: '✍️', k: ['escrevendo assinatura', 'escribiendo firma', 'writing hand signature'] },
      { e: '💅', k: ['unha esmalte', 'una esmalte', 'nail polish manicure'] },
      { e: '💪', k: ['forca musculo biceps academia', 'fuerza musculo biceps gimnasio', 'muscle flex strong biceps gym'] },
      { e: '🦵', k: ['perna', 'pierna', 'leg'] },
      { e: '👀', k: ['olhos olhando atencao', 'ojos mirando atencion', 'eyes looking watching'] },
      { e: '👁️', k: ['olho', 'ojo', 'eye'] },
      { e: '👄', k: ['boca labios', 'boca labios', 'mouth lips'] },
      { e: '👅', k: ['lingua', 'lengua', 'tongue'] },
      { e: '👶', k: ['bebe crianca', 'bebe nino', 'baby infant'] },
      { e: '🧒', k: ['crianca', 'nino criatura', 'child kid'] },
      { e: '👦', k: ['menino garoto', 'nino chico', 'boy'] },
      { e: '👧', k: ['menina garota', 'nina chica', 'girl'] },
      { e: '🧑', k: ['pessoa adulto', 'persona adulto', 'person adult'] },
      { e: '👨', k: ['homem', 'hombre', 'man'] },
      { e: '👩', k: ['mulher', 'mujer', 'woman'] },
      { e: '🧓', k: ['idoso pessoa mais velha', 'mayor persona anciana', 'older person elderly'] },
      { e: '👴', k: ['senhor idoso vovo', 'senor anciano abuelo', 'old man grandpa'] },
      { e: '👵', k: ['senhora idosa vovo', 'senora anciana abuela', 'old woman grandma'] },
      { e: '👮', k: ['policial', 'policia', 'police officer cop'] },
      { e: '👷', k: ['operario obra construcao', 'obrero obra construccion', 'construction worker builder'] },
      { e: '💂', k: ['guarda', 'guardia', 'guard'] },
      { e: '🕵️', k: ['detetive espiao', 'detective espia', 'detective spy sleuth'] },
      { e: '👩‍⚕️', k: ['medica enfermeira saude', 'medica enfermera salud', 'woman doctor nurse health'] },
      { e: '👨‍⚕️', k: ['medico enfermeiro saude', 'medico enfermero salud', 'man doctor nurse health'] },
      { e: '👩‍🏫', k: ['professora escola', 'profesora escuela', 'woman teacher school'] },
      { e: '👨‍🏫', k: ['professor escola', 'profesor escuela', 'man teacher school'] },
      { e: '👩‍💻', k: ['programadora tecnologia trabalho', 'programadora tecnologia trabajo', 'woman developer coder tech'] },
      { e: '👨‍💻', k: ['programador tecnologia trabalho', 'programador tecnologia trabajo', 'man developer coder tech'] },
      { e: '👩‍💼', k: ['executiva escritorio trabalho', 'ejecutiva oficina trabajo', 'businesswoman office work'] },
      { e: '👨‍💼', k: ['executivo escritorio trabalho', 'ejecutivo oficina trabajo', 'businessman office work'] },
      { e: '🤵', k: ['terno smoking casamento', 'traje esmoquin boda', 'tuxedo suit wedding'] },
      { e: '👰', k: ['noiva casamento veu', 'novia boda velo', 'bride wedding veil'] },
      { e: '🤰', k: ['gravida gestante', 'embarazada gestante', 'pregnant expecting'] },
      { e: '🎅', k: ['papai noel natal', 'papa noel navidad', 'santa claus christmas'] },
      { e: '🦸', k: ['super heroi', 'superheroe', 'superhero'] },
      { e: '🧙', k: ['mago bruxo magia', 'mago brujo magia', 'mage wizard magic'] },
      { e: '🧚', k: ['fada magia', 'hada magia', 'fairy magic'] },
      { e: '💁', k: ['informacao atendente ombro', 'informacion recepcionista hombro', 'information desk tipping hand'] },
      { e: '🙋', k: ['levantando a mao presente eu', 'levantando la mano presente yo', 'raising hand here me'] },
      { e: '🙇', k: ['reverencia desculpa respeito', 'reverencia disculpa respeto', 'bowing sorry respect'] },
      { e: '🤦', k: ['facepalm mao na testa descrenca', 'facepalm mano en la cara incredulidad', 'facepalm disbelief ugh'] },
      { e: '🤷', k: ['ombros sei la tanto faz', 'hombros ni idea da igual', 'shrug dunno whatever'] },
      { e: '🙅', k: ['nao proibido negando', 'no prohibido negando', 'no gesture forbidden refuse'] },
      { e: '🙆', k: ['ok certo positivo', 'ok correcto positivo', 'ok gesture yes correct'] },
      { e: '💇', k: ['corte de cabelo salao', 'corte de pelo peluqueria', 'haircut salon'] },
      { e: '🚶', k: ['andando caminhando pedestre', 'andando caminando peaton', 'walking pedestrian'] },
      { e: '🏃', k: ['correndo corrida pressa', 'corriendo carrera prisa', 'running run hurry'] },
      { e: '💃', k: ['danca mulher festa', 'baile mujer fiesta', 'dancer woman party'] },
      { e: '🕺', k: ['danca homem festa', 'baile hombre fiesta', 'dancer man party'] },
      { e: '👯', k: ['dupla festa orelhas de coelho', 'pareja fiesta orejas de conejo', 'partying bunny ears dancers'] },
      { e: '👪', k: ['familia', 'familia', 'family'] },
      { e: '👫', k: ['casal de maos dadas', 'pareja de la mano', 'couple holding hands'] },
      { e: '💑', k: ['casal apaixonado', 'pareja enamorada', 'couple with heart love'] },
      { e: '💏', k: ['casal beijando', 'pareja besandose', 'kiss couple'] },
    ],
  },
  {
    id: 'natureza',
    label: 'emoji.catAnimais',
    icon: '🐻',
    items: [
      { e: '🐶', k: ['cachorro cao dog', 'perro can', 'dog puppy'] },
      { e: '🐱', k: ['gato gata cat', 'gato gata minino', 'cat kitten'] },
      { e: '🐭', k: ['rato camundongo', 'raton', 'mouse'] },
      { e: '🐹', k: ['hamster', 'hamster', 'hamster'] },
      { e: '🐰', k: ['coelho', 'conejo', 'rabbit bunny'] },
      { e: '🦊', k: ['raposa', 'zorro', 'fox'] },
      { e: '🐻', k: ['urso', 'oso', 'bear'] },
      { e: '🐼', k: ['panda', 'panda', 'panda'] },
      { e: '🐨', k: ['coala', 'koala', 'koala'] },
      { e: '🐯', k: ['tigre', 'tigre', 'tiger'] },
      { e: '🦁', k: ['leao', 'leon', 'lion'] },
      { e: '🐮', k: ['vaca boi', 'vaca buey', 'cow'] },
      { e: '🐷', k: ['porco', 'cerdo', 'pig'] },
      { e: '🐸', k: ['sapo ra', 'rana sapo', 'frog'] },
      { e: '🐵', k: ['macaco', 'mono', 'monkey'] },
      { e: '🐔', k: ['galinha', 'gallina', 'chicken hen'] },
      { e: '🐧', k: ['pinguim', 'pinguino', 'penguin'] },
      { e: '🐦', k: ['passaro ave', 'pajaro ave', 'bird'] },
      { e: '🐤', k: ['pintinho', 'pollito', 'chick baby chicken'] },
      { e: '🦆', k: ['pato', 'pato', 'duck'] },
      { e: '🦅', k: ['aguia', 'aguila', 'eagle'] },
      { e: '🦉', k: ['coruja', 'buho lechuza', 'owl'] },
      { e: '🦇', k: ['morcego', 'murcielago', 'bat'] },
      { e: '🐺', k: ['lobo', 'lobo', 'wolf'] },
      { e: '🐗', k: ['javali', 'jabali', 'boar'] },
      { e: '🐴', k: ['cavalo', 'caballo', 'horse'] },
      { e: '🦄', k: ['unicornio magia', 'unicornio magia', 'unicorn magic'] },
      { e: '🐝', k: ['abelha mel', 'abeja miel', 'bee honey'] },
      { e: '🐛', k: ['lagarta bug inseto', 'oruga bicho insecto', 'caterpillar bug insect'] },
      { e: '🦋', k: ['borboleta', 'mariposa', 'butterfly'] },
      { e: '🐌', k: ['caracol lesma devagar', 'caracol babosa lento', 'snail slow'] },
      { e: '🐞', k: ['joaninha', 'mariquita', 'ladybug'] },
      { e: '🐜', k: ['formiga', 'hormiga', 'ant'] },
      { e: '🕷️', k: ['aranha', 'arana', 'spider'] },
      { e: '🦂', k: ['escorpiao', 'escorpion', 'scorpion'] },
      { e: '🐢', k: ['tartaruga', 'tortuga', 'turtle tortoise'] },
      { e: '🐍', k: ['cobra serpente', 'serpiente culebra', 'snake serpent'] },
      { e: '🦎', k: ['lagarto', 'lagarto lagartija', 'lizard'] },
      { e: '🐙', k: ['polvo', 'pulpo', 'octopus'] },
      { e: '🦐', k: ['camarao', 'gamba camaron', 'shrimp'] },
      { e: '🦀', k: ['caranguejo', 'cangrejo', 'crab'] },
      { e: '🐠', k: ['peixe tropical', 'pez tropical', 'tropical fish'] },
      { e: '🐟', k: ['peixe', 'pez pescado', 'fish'] },
      { e: '🐬', k: ['golfinho', 'delfin', 'dolphin'] },
      { e: '🐳', k: ['baleia', 'ballena', 'whale'] },
      { e: '🦈', k: ['tubarao', 'tiburon', 'shark'] },
      { e: '🐊', k: ['crocodilo jacare', 'cocodrilo caiman', 'crocodile alligator'] },
      { e: '🐘', k: ['elefante', 'elefante', 'elephant'] },
      { e: '🦏', k: ['rinoceronte', 'rinoceronte', 'rhinoceros rhino'] },
      { e: '🐫', k: ['camelo', 'camello', 'camel'] },
      { e: '🦒', k: ['girafa', 'jirafa', 'giraffe'] },
      { e: '🐆', k: ['onca leopardo', 'leopardo jaguar', 'leopard'] },
      { e: '🐄', k: ['vaca gado', 'vaca ganado', 'cow cattle'] },
      { e: '🐖', k: ['porco suino', 'cerdo porcino', 'pig hog'] },
      { e: '🐑', k: ['ovelha', 'oveja', 'sheep ewe'] },
      { e: '🐐', k: ['cabra bode', 'cabra chivo', 'goat'] },
      { e: '🐓', k: ['galo', 'gallo', 'rooster'] },
      { e: '🦃', k: ['peru', 'pavo', 'turkey'] },
      { e: '🕊️', k: ['pomba paz', 'paloma paz', 'dove peace'] },
      { e: '🐕', k: ['cachorro cao', 'perro can', 'dog'] },
      { e: '🐈', k: ['gato', 'gato', 'cat'] },
      { e: '🐇', k: ['coelho', 'conejo', 'rabbit'] },
      { e: '🐁', k: ['rato', 'raton', 'mouse rat'] },
      { e: '🌵', k: ['cacto deserto', 'cactus desierto', 'cactus desert'] },
      { e: '🌲', k: ['pinheiro arvore', 'pino arbol', 'evergreen pine tree'] },
      { e: '🌳', k: ['arvore', 'arbol', 'tree'] },
      { e: '🌴', k: ['coqueiro palmeira praia', 'palmera playa', 'palm tree beach'] },
      { e: '🌱', k: ['muda broto crescimento', 'brote plantula crecimiento', 'seedling sprout growth'] },
      { e: '🌿', k: ['erva folha planta', 'hierba hoja planta', 'herb leaf plant'] },
      { e: '☘️', k: ['trevo sorte', 'trebol suerte', 'shamrock clover luck'] },
      { e: '🍀', k: ['trevo quatro folhas sorte', 'trebol cuatro hojas suerte', 'four leaf clover luck'] },
      { e: '🍁', k: ['folha outono', 'hoja otono arce', 'maple leaf autumn fall'] },
      { e: '🍂', k: ['folhas caidas outono', 'hojas caidas otono', 'fallen leaves autumn'] },
      { e: '🍃', k: ['folhas vento', 'hojas viento', 'leaves wind'] },
      { e: '🌷', k: ['tulipa flor', 'tulipan flor', 'tulip flower'] },
      { e: '🌹', k: ['rosa flor amor', 'rosa flor amor', 'rose flower love'] },
      { e: '🥀', k: ['flor murcha', 'flor marchita', 'wilted flower'] },
      { e: '🌺', k: ['hibisco flor', 'hibisco flor', 'hibiscus flower'] },
      { e: '🌸', k: ['flor de cerejeira sakura', 'flor de cerezo sakura', 'cherry blossom sakura'] },
      { e: '🌼', k: ['margarida flor', 'margarita flor', 'blossom daisy flower'] },
      { e: '🌻', k: ['girassol flor', 'girasol flor', 'sunflower'] },
      { e: '🌞', k: ['sol sorrindo', 'sol sonriendo', 'sun with face smiling'] },
      { e: '🌝', k: ['lua cheia rosto', 'luna llena cara', 'full moon face'] },
      { e: '🌚', k: ['lua nova rosto', 'luna nueva cara', 'new moon face'] },
      { e: '🌙', k: ['lua noite', 'luna noche', 'crescent moon night'] },
      { e: '⭐', k: ['estrela', 'estrella', 'star'] },
      { e: '🌟', k: ['estrela brilhante', 'estrella brillante', 'glowing star bright'] },
      { e: '✨', k: ['brilho estrelas magia novo', 'brillo estrellas magia nuevo', 'sparkles shine magic new'] },
      { e: '⚡', k: ['raio energia rapido', 'rayo energia rapido', 'lightning bolt energy fast'] },
      { e: '🔥', k: ['fogo chama incrivel top', 'fuego llama increible', 'fire flame lit hot'] },
      { e: '🌈', k: ['arco iris', 'arco iris', 'rainbow'] },
      { e: '☀️', k: ['sol tempo bom', 'sol buen tiempo', 'sun sunny weather'] },
      { e: '⛅', k: ['sol e nuvem tempo', 'sol y nube tiempo', 'sun behind cloud partly cloudy'] },
      { e: '☁️', k: ['nuvem nublado', 'nube nublado', 'cloud cloudy'] },
      { e: '🌧️', k: ['chuva', 'lluvia', 'rain rainy'] },
      { e: '⛈️', k: ['tempestade trovao', 'tormenta trueno', 'thunderstorm storm'] },
      { e: '❄️', k: ['neve floco frio', 'nieve copo frio', 'snowflake snow cold'] },
      { e: '☃️', k: ['boneco de neve', 'muneco de nieve', 'snowman'] },
      { e: '💧', k: ['gota agua', 'gota agua', 'droplet water'] },
      { e: '🌊', k: ['onda mar praia', 'ola mar playa', 'wave ocean sea'] },
      { e: '🌍', k: ['terra mundo planeta', 'tierra mundo planeta', 'earth globe world planet'] },
      { e: '🌎', k: ['terra americas mundo', 'tierra americas mundo', 'earth americas globe'] },
      { e: '🌏', k: ['terra asia mundo', 'tierra asia mundo', 'earth asia globe'] },
      { e: '🌪️', k: ['tornado furacao', 'tornado huracan', 'tornado hurricane'] },
      { e: '🌫️', k: ['neblina nevoeiro', 'niebla bruma', 'fog mist'] },
    ],
  },
  {
    id: 'comida',
    label: 'emoji.catComidas',
    icon: '🍔',
    items: [
      { e: '🍎', k: ['maca fruta', 'manzana fruta', 'apple fruit'] },
      { e: '🍏', k: ['maca verde fruta', 'manzana verde fruta', 'green apple fruit'] },
      { e: '🍐', k: ['pera fruta', 'pera fruta', 'pear fruit'] },
      { e: '🍊', k: ['laranja fruta', 'naranja fruta', 'orange tangerine fruit'] },
      { e: '🍋', k: ['limao fruta', 'limon fruta', 'lemon fruit'] },
      { e: '🍌', k: ['banana fruta', 'platano banana fruta', 'banana fruit'] },
      { e: '🍉', k: ['melancia fruta', 'sandia fruta', 'watermelon fruit'] },
      { e: '🍇', k: ['uva fruta', 'uva fruta', 'grapes fruit'] },
      { e: '🍓', k: ['morango fruta', 'fresa frutilla fruta', 'strawberry fruit'] },
      { e: '🫐', k: ['mirtilo fruta', 'arandano fruta', 'blueberries fruit'] },
      { e: '🍈', k: ['melao fruta', 'melon fruta', 'melon fruit'] },
      { e: '🍒', k: ['cereja fruta', 'cereza fruta', 'cherries fruit'] },
      { e: '🍑', k: ['pessego fruta bumbum', 'melocoton durazno fruta', 'peach fruit butt'] },
      { e: '🥭', k: ['manga fruta', 'mango fruta', 'mango fruit'] },
      { e: '🍍', k: ['abacaxi fruta', 'pina fruta', 'pineapple fruit'] },
      { e: '🥥', k: ['coco fruta', 'coco fruta', 'coconut fruit'] },
      { e: '🥝', k: ['kiwi fruta', 'kiwi fruta', 'kiwi fruit'] },
      { e: '🍅', k: ['tomate', 'tomate', 'tomato'] },
      { e: '🥑', k: ['abacate', 'aguacate palta', 'avocado'] },
      { e: '🍆', k: ['berinjela', 'berenjena', 'eggplant aubergine'] },
      { e: '🥔', k: ['batata', 'patata papa', 'potato'] },
      { e: '🥕', k: ['cenoura', 'zanahoria', 'carrot'] },
      { e: '🌽', k: ['milho', 'maiz', 'corn maize'] },
      { e: '🌶️', k: ['pimenta apimentado', 'chile picante guindilla', 'chili pepper hot spicy'] },
      { e: '🥒', k: ['pepino', 'pepino', 'cucumber'] },
      { e: '🥬', k: ['alface verdura', 'lechuga verdura', 'lettuce greens'] },
      { e: '🥦', k: ['brocolis', 'brocoli', 'broccoli'] },
      { e: '🧄', k: ['alho', 'ajo', 'garlic'] },
      { e: '🧅', k: ['cebola', 'cebolla', 'onion'] },
      { e: '🍄', k: ['cogumelo', 'champinon seta hongo', 'mushroom'] },
      { e: '🥜', k: ['amendoim', 'cacahuete mani', 'peanuts'] },
      { e: '🌰', k: ['castanha', 'castana', 'chestnut'] },
      { e: '🍞', k: ['pao', 'pan', 'bread loaf'] },
      { e: '🥐', k: ['croissant', 'cruasan', 'croissant'] },
      { e: '🥖', k: ['baguete pao', 'baguete pan', 'baguette bread'] },
      { e: '🥨', k: ['pretzel', 'pretzel', 'pretzel'] },
      { e: '🧀', k: ['queijo', 'queso', 'cheese'] },
      { e: '🥚', k: ['ovo', 'huevo', 'egg'] },
      { e: '🍳', k: ['ovo frito cafe da manha', 'huevo frito desayuno', 'fried egg breakfast'] },
      { e: '🥞', k: ['panqueca', 'tortita panqueque', 'pancakes'] },
      { e: '🧇', k: ['waffle', 'gofre', 'waffle'] },
      { e: '🥓', k: ['bacon', 'bacon panceta tocino', 'bacon'] },
      { e: '🍗', k: ['frango coxa', 'pollo muslo', 'poultry leg chicken drumstick'] },
      { e: '🍖', k: ['carne osso churrasco', 'carne hueso barbacoa', 'meat bone barbecue ribs'] },
      { e: '🌭', k: ['cachorro quente hot dog', 'perrito caliente', 'hot dog'] },
      { e: '🍔', k: ['hamburguer lanche', 'hamburguesa', 'hamburger burger'] },
      { e: '🍟', k: ['batata frita', 'patatas fritas', 'french fries chips'] },
      { e: '🍕', k: ['pizza', 'pizza', 'pizza'] },
      { e: '🥪', k: ['sanduiche', 'sandwich bocadillo', 'sandwich'] },
      { e: '🌮', k: ['taco', 'taco', 'taco'] },
      { e: '🌯', k: ['burrito wrap', 'burrito wrap', 'burrito wrap'] },
      { e: '🥗', k: ['salada', 'ensalada', 'salad'] },
      { e: '🥘', k: ['panela comida', 'cazuela comida', 'pan of food paella'] },
      { e: '🍝', k: ['macarrao espaguete massa', 'pasta espagueti', 'spaghetti pasta'] },
      { e: '🍜', k: ['lamen sopa macarrao', 'ramen sopa fideos', 'ramen noodles soup'] },
      { e: '🍲', k: ['sopa caldo', 'sopa caldo', 'stew soup'] },
      { e: '🍛', k: ['arroz curry', 'arroz con curry', 'curry rice'] },
      { e: '🍣', k: ['sushi', 'sushi', 'sushi'] },
      { e: '🍤', k: ['camarao frito tempura', 'gamba frita tempura', 'fried shrimp tempura'] },
      { e: '🥟', k: ['guioza pastel', 'empanadilla gyoza', 'dumpling gyoza'] },
      { e: '🍚', k: ['arroz', 'arroz', 'rice'] },
      { e: '🍱', k: ['marmita bento', 'fiambrera bento', 'bento box lunch'] },
      { e: '🥩', k: ['carne bife picanha', 'carne filete bistec', 'steak meat cut'] },
      { e: '🍦', k: ['sorvete casquinha', 'helado cucurucho', 'ice cream cone soft serve'] },
      { e: '🍧', k: ['raspadinha gelo', 'granizado hielo', 'shaved ice snow cone'] },
      { e: '🍨', k: ['sorvete taca', 'helado copa', 'ice cream bowl'] },
      { e: '🍩', k: ['rosquinha donut', 'rosquilla donut', 'doughnut donut'] },
      { e: '🍪', k: ['biscoito cookie', 'galleta', 'cookie biscuit'] },
      { e: '🎂', k: ['bolo aniversario', 'tarta cumpleanos', 'birthday cake'] },
      { e: '🍰', k: ['fatia de bolo', 'porcion de tarta', 'slice of cake shortcake'] },
      { e: '🧁', k: ['cupcake', 'magdalena cupcake', 'cupcake'] },
      { e: '🥧', k: ['torta', 'tarta pastel', 'pie'] },
      { e: '🍫', k: ['chocolate', 'chocolate', 'chocolate bar'] },
      { e: '🍬', k: ['bala doce', 'caramelo dulce', 'candy sweet'] },
      { e: '🍭', k: ['pirulito', 'piruleta chupachups', 'lollipop'] },
      { e: '🍮', k: ['pudim', 'flan pudin', 'custard pudding flan'] },
      { e: '🍯', k: ['mel', 'miel', 'honey'] },
      { e: '🍿', k: ['pipoca cinema', 'palomitas cine', 'popcorn cinema'] },
      { e: '🧂', k: ['sal', 'sal', 'salt'] },
      { e: '🥛', k: ['leite copo', 'leche vaso', 'milk glass'] },
      { e: '☕', k: ['cafe cafezinho quente', 'cafe caliente', 'coffee hot drink'] },
      { e: '🍵', k: ['cha', 'te', 'tea'] },
      { e: '🧃', k: ['suco caixinha', 'zumo jugo brik', 'juice box'] },
      { e: '🥤', k: ['refrigerante copo', 'refresco vaso', 'soda cup drink'] },
      { e: '🍺', k: ['cerveja chopp', 'cerveza', 'beer'] },
      { e: '🍻', k: ['cervejas brinde', 'cervezas brindis', 'cheers beers'] },
      { e: '🥂', k: ['brinde tacas comemoracao', 'brindis copas celebracion', 'toast clinking glasses celebrate'] },
      { e: '🍷', k: ['vinho taca', 'vino copa', 'wine glass'] },
      { e: '🥃', k: ['whisky dose', 'whisky chupito', 'whiskey tumbler shot'] },
      { e: '🍸', k: ['drink coquetel martini', 'copa coctel martini', 'cocktail martini drink'] },
      { e: '🍹', k: ['drink tropical', 'bebida tropical', 'tropical drink'] },
      { e: '🍾', k: ['champanhe comemoracao', 'champan celebracion', 'champagne bottle celebrate'] },
      { e: '🧉', k: ['chimarrao mate', 'mate yerba', 'mate drink'] },
      { e: '🥄', k: ['colher', 'cuchara', 'spoon'] },
      { e: '🍴', k: ['garfo e faca comer', 'tenedor y cuchillo comer', 'fork and knife eat'] },
      { e: '🍽️', k: ['prato talheres jantar', 'plato cubiertos cena', 'plate cutlery dinner'] },
    ],
  },
  {
    id: 'atividades',
    label: 'emoji.catAtividades',
    icon: '⚽',
    items: [
      { e: '⚽', k: ['futebol bola', 'futbol balon', 'soccer football ball'] },
      { e: '🏀', k: ['basquete bola', 'baloncesto basquet pelota', 'basketball'] },
      { e: '🏈', k: ['futebol americano', 'futbol americano', 'american football'] },
      { e: '⚾', k: ['beisebol', 'beisbol', 'baseball'] },
      { e: '🥎', k: ['softbol', 'softbol', 'softball'] },
      { e: '🎾', k: ['tenis', 'tenis', 'tennis'] },
      { e: '🏐', k: ['volei', 'voleibol', 'volleyball'] },
      { e: '🏉', k: ['rugby', 'rugby', 'rugby'] },
      { e: '🎱', k: ['sinuca bilhar', 'billar bola ocho', 'pool billiards eight ball'] },
      { e: '🏓', k: ['ping pong tenis de mesa', 'ping pong tenis de mesa', 'ping pong table tennis'] },
      { e: '🏸', k: ['badminton', 'badminton', 'badminton'] },
      { e: '🥅', k: ['gol trave', 'porteria gol red', 'goal net'] },
      { e: '🏒', k: ['hoquei', 'hockey', 'ice hockey'] },
      { e: '🏑', k: ['hoquei grama', 'hockey hierba', 'field hockey'] },
      { e: '🥍', k: ['lacrosse', 'lacrosse', 'lacrosse'] },
      { e: '🏏', k: ['criquete', 'criquet', 'cricket'] },
      { e: '⛳', k: ['golfe', 'golf', 'golf'] },
      { e: '🏹', k: ['arco e flecha', 'arco y flecha tiro', 'bow and arrow archery'] },
      { e: '🎣', k: ['pesca', 'pesca cana', 'fishing pole'] },
      { e: '🤿', k: ['mergulho', 'buceo mascara', 'diving mask snorkel'] },
      { e: '🥊', k: ['boxe luva', 'boxeo guante', 'boxing glove'] },
      { e: '🥋', k: ['artes marciais judo karate', 'artes marciales judo karate', 'martial arts judo karate'] },
      { e: '🎽', k: ['corrida camiseta', 'carrera camiseta', 'running shirt sash'] },
      { e: '🛹', k: ['skate', 'monopatin skate', 'skateboard'] },
      { e: '🛼', k: ['patins', 'patines', 'roller skate'] },
      { e: '⛸️', k: ['patinacao no gelo', 'patinaje sobre hielo', 'ice skate'] },
      { e: '🎿', k: ['esqui', 'esqui', 'ski'] },
      { e: '🏂', k: ['snowboard', 'snowboard', 'snowboard'] },
      { e: '🏋️', k: ['academia musculacao peso', 'gimnasio pesas musculacion', 'weight lifting gym workout'] },
      { e: '🤸', k: ['ginastica cambalhota', 'gimnasia voltereta', 'cartwheel gymnastics'] },
      { e: '🤼', k: ['luta', 'lucha', 'wrestling'] },
      { e: '🤽', k: ['polo aquatico', 'waterpolo', 'water polo'] },
      { e: '🤾', k: ['handebol', 'balonmano', 'handball'] },
      { e: '🧘', k: ['ioga meditacao calma', 'yoga meditacion calma', 'yoga meditation lotus calm'] },
      { e: '🏊', k: ['natacao nadando', 'natacion nadando', 'swimming swim'] },
      { e: '🚴', k: ['ciclismo bicicleta', 'ciclismo bicicleta', 'cycling bike'] },
      { e: '🚵', k: ['mountain bike', 'bici de montana', 'mountain biking'] },
      { e: '🏆', k: ['trofeu vitoria campeao premio', 'trofeo victoria campeon premio', 'trophy win champion award'] },
      { e: '🥇', k: ['medalha ouro primeiro', 'medalla oro primero', 'gold medal first place'] },
      { e: '🥈', k: ['medalha prata segundo', 'medalla plata segundo', 'silver medal second place'] },
      { e: '🥉', k: ['medalha bronze terceiro', 'medalla bronce tercero', 'bronze medal third place'] },
      { e: '🏅', k: ['medalha premio', 'medalla premio', 'sports medal award'] },
      { e: '🎖️', k: ['medalha militar honra', 'medalla militar honor', 'military medal honor'] },
      { e: '🎯', k: ['alvo meta objetivo', 'diana objetivo meta', 'target bullseye goal'] },
      { e: '🎲', k: ['dado sorte jogo', 'dado suerte juego', 'dice die game luck'] },
      { e: '🎰', k: ['caca niquel sorte', 'tragaperras suerte', 'slot machine gambling'] },
      { e: '🎳', k: ['boliche', 'bolos', 'bowling'] },
      { e: '🎮', k: ['videogame controle jogo', 'videojuego mando juego', 'video game controller gaming'] },
      { e: '🕹️', k: ['joystick arcade', 'joystick arcade', 'joystick arcade'] },
      { e: '🧩', k: ['quebra cabeca peca', 'rompecabezas puzle pieza', 'puzzle piece jigsaw'] },
      { e: '🎨', k: ['arte pintura paleta', 'arte pintura paleta', 'art palette painting'] },
      { e: '🎭', k: ['teatro mascaras', 'teatro mascaras', 'theater masks drama'] },
      { e: '🎤', k: ['microfone cantar karaoke', 'microfono cantar karaoke', 'microphone sing karaoke'] },
      { e: '🎧', k: ['fone de ouvido musica', 'auriculares musica', 'headphones music'] },
      { e: '🎼', k: ['partitura musica', 'partitura musica', 'musical score sheet music'] },
      { e: '🎵', k: ['nota musical musica', 'nota musical musica', 'musical note music'] },
      { e: '🎶', k: ['notas musicais musica', 'notas musicales musica', 'musical notes music'] },
      { e: '🎹', k: ['piano teclado', 'piano teclado', 'piano keyboard'] },
      { e: '🥁', k: ['bateria tambor', 'bateria tambor', 'drum'] },
      { e: '🎸', k: ['guitarra violao', 'guitarra', 'guitar'] },
      { e: '🎺', k: ['trompete', 'trompeta', 'trumpet'] },
      { e: '🎻', k: ['violino', 'violin', 'violin'] },
      { e: '🪗', k: ['acordeao sanfona', 'acordeon', 'accordion'] },
      { e: '🎬', k: ['cinema claquete filme', 'cine claqueta pelicula', 'clapper board movie film'] },
      { e: '🎪', k: ['circo', 'circo carpa', 'circus tent'] },
      { e: '🎉', k: ['festa comemoracao parabens', 'fiesta celebracion felicidades', 'party popper celebrate congrats'] },
      { e: '🎊', k: ['confete festa', 'confeti fiesta', 'confetti ball party'] },
      { e: '🎈', k: ['balao festa', 'globo fiesta', 'balloon party'] },
      { e: '🎁', k: ['presente aniversario', 'regalo cumpleanos', 'gift present birthday'] },
      { e: '🎀', k: ['laco fita', 'lazo cinta', 'ribbon bow'] },
      { e: '🎄', k: ['arvore de natal', 'arbol de navidad', 'christmas tree'] },
      { e: '🎇', k: ['fogos de artificio', 'fuegos artificiales', 'sparkler fireworks'] },
      { e: '🎆', k: ['fogos de artificio festa', 'fuegos artificiales fiesta', 'fireworks party'] },
      { e: '🧨', k: ['dinamite explosivo', 'dinamita explosivo', 'firecracker dynamite'] },
      { e: '🪅', k: ['pinhata festa', 'pinata fiesta', 'pinata party'] },
    ],
  },
  {
    id: 'viagens',
    label: 'emoji.catViagens',
    icon: '🚗',
    items: [
      { e: '🚗', k: ['carro automovel', 'coche auto automovil', 'car automobile'] },
      { e: '🚕', k: ['taxi', 'taxi', 'taxi cab'] },
      { e: '🚙', k: ['suv carro', 'todoterreno suv coche', 'suv recreational vehicle'] },
      { e: '🚌', k: ['onibus', 'autobus bus', 'bus'] },
      { e: '🚎', k: ['trolebus onibus', 'trolebus autobus', 'trolleybus'] },
      { e: '🏎️', k: ['carro de corrida formula 1', 'coche de carreras formula 1', 'race car formula one'] },
      { e: '🚓', k: ['viatura policia', 'patrulla policia', 'police car'] },
      { e: '🚑', k: ['ambulancia', 'ambulancia', 'ambulance'] },
      { e: '🚒', k: ['bombeiro caminhao', 'bomberos camion', 'fire engine truck'] },
      { e: '🚐', k: ['van', 'furgoneta', 'minibus van'] },
      { e: '🚚', k: ['caminhao entrega', 'camion reparto', 'delivery truck'] },
      { e: '🚛', k: ['carreta caminhao', 'camion trailer', 'articulated lorry semi truck'] },
      { e: '🚜', k: ['trator', 'tractor', 'tractor'] },
      { e: '🛵', k: ['moto scooter entrega', 'moto scooter reparto', 'scooter motor delivery'] },
      { e: '🏍️', k: ['moto motocicleta', 'moto motocicleta', 'motorcycle'] },
      { e: '🚲', k: ['bicicleta bike', 'bicicleta bici', 'bicycle bike'] },
      { e: '🛴', k: ['patinete', 'patinete', 'kick scooter'] },
      { e: '🚉', k: ['estacao trem', 'estacion tren', 'train station'] },
      { e: '🚄', k: ['trem bala', 'tren bala alta velocidad', 'bullet train high speed'] },
      { e: '🚆', k: ['trem', 'tren', 'train'] },
      { e: '🚇', k: ['metro', 'metro', 'metro subway'] },
      { e: '🚊', k: ['bonde vlt', 'tranvia', 'tram streetcar'] },
      { e: '✈️', k: ['aviao voo viagem', 'avion vuelo viaje', 'airplane flight travel'] },
      { e: '🛫', k: ['decolagem aviao', 'despegue avion', 'departure takeoff plane'] },
      { e: '🛬', k: ['pouso aviao', 'aterrizaje avion', 'arrival landing plane'] },
      { e: '🚁', k: ['helicoptero', 'helicoptero', 'helicopter'] },
      { e: '🚀', k: ['foguete lancamento decolar', 'cohete lanzamiento despegar', 'rocket launch liftoff'] },
      { e: '🛸', k: ['disco voador ovni', 'platillo volante ovni', 'flying saucer ufo'] },
      { e: '⛵', k: ['veleiro barco', 'velero barco', 'sailboat'] },
      { e: '🚤', k: ['lancha barco', 'lancha barco', 'speedboat'] },
      { e: '🛳️', k: ['navio cruzeiro', 'barco crucero', 'passenger ship cruise'] },
      { e: '⛴️', k: ['balsa ferry', 'transbordador ferry', 'ferry'] },
      { e: '🚢', k: ['navio', 'barco buque', 'ship'] },
      { e: '⚓', k: ['ancora', 'ancla', 'anchor'] },
      { e: '⛽', k: ['posto gasolina combustivel', 'gasolinera combustible', 'fuel pump gas station'] },
      { e: '🚦', k: ['semaforo transito', 'semaforo trafico', 'traffic light'] },
      { e: '🚧', k: ['obras construcao', 'obras construccion', 'construction sign roadworks'] },
      { e: '🗺️', k: ['mapa viagem', 'mapa viaje', 'world map travel'] },
      { e: '🧭', k: ['bussola direcao', 'brujula direccion', 'compass direction'] },
      { e: '🏔️', k: ['montanha neve', 'montana nieve', 'snow capped mountain'] },
      { e: '⛰️', k: ['montanha', 'montana', 'mountain'] },
      { e: '🌋', k: ['vulcao', 'volcan', 'volcano'] },
      { e: '🏕️', k: ['acampamento camping', 'campamento camping', 'camping tent'] },
      { e: '🏖️', k: ['praia guarda sol', 'playa sombrilla', 'beach umbrella'] },
      { e: '🏜️', k: ['deserto', 'desierto', 'desert'] },
      { e: '🏝️', k: ['ilha praia', 'isla playa', 'desert island beach'] },
      { e: '🏟️', k: ['estadio', 'estadio', 'stadium'] },
      { e: '🏛️', k: ['monumento classico', 'monumento clasico', 'classical building monument'] },
      { e: '🏗️', k: ['construcao obra', 'construccion obra', 'building construction site'] },
      { e: '🏘️', k: ['casas bairro', 'casas barrio', 'houses neighborhood'] },
      { e: '🏠', k: ['casa lar', 'casa hogar', 'house home'] },
      { e: '🏡', k: ['casa jardim', 'casa jardin', 'house with garden'] },
      { e: '🏢', k: ['escritorio predio empresa', 'oficina edificio empresa', 'office building company'] },
      { e: '🏣', k: ['correios japao', 'correos japon', 'japanese post office'] },
      { e: '🏥', k: ['hospital', 'hospital', 'hospital'] },
      { e: '🏦', k: ['banco', 'banco', 'bank'] },
      { e: '🏨', k: ['hotel', 'hotel', 'hotel'] },
      { e: '🏪', k: ['loja conveniencia', 'tienda 24 horas', 'convenience store shop'] },
      { e: '🏫', k: ['escola', 'escuela colegio', 'school'] },
      { e: '🏭', k: ['fabrica industria', 'fabrica industria', 'factory industry'] },
      { e: '🏬', k: ['shopping loja', 'centro comercial tienda', 'department store mall shop'] },
      { e: '💒', k: ['casamento igreja', 'boda iglesia', 'wedding chapel'] },
      { e: '⛪', k: ['igreja', 'iglesia', 'church'] },
      { e: '🕌', k: ['mesquita', 'mezquita', 'mosque'] },
      { e: '🕍', k: ['sinagoga', 'sinagoga', 'synagogue'] },
      { e: '🗽', k: ['estatua da liberdade nova york', 'estatua de la libertad nueva york', 'statue of liberty new york'] },
      { e: '🗼', k: ['torre de toquio', 'torre de tokio', 'tokyo tower'] },
      { e: '🏰', k: ['castelo', 'castillo', 'castle'] },
      { e: '🌁', k: ['neblina cidade', 'niebla ciudad', 'foggy city'] },
      { e: '🌃', k: ['cidade a noite', 'ciudad de noche', 'night with stars city'] },
      { e: '🌆', k: ['cidade entardecer', 'ciudad atardecer', 'cityscape dusk'] },
      { e: '🌇', k: ['por do sol cidade', 'puesta de sol ciudad', 'sunset city'] },
      { e: '🌉', k: ['ponte noite', 'puente noche', 'bridge at night'] },
      { e: '🎡', k: ['roda gigante parque', 'noria parque', 'ferris wheel amusement park'] },
      { e: '🎢', k: ['montanha russa parque', 'montana rusa parque', 'roller coaster amusement park'] },
      { e: '🎠', k: ['carrossel', 'carrusel tiovivo', 'carousel merry go round'] },
      { e: '⛲', k: ['chafariz fonte', 'fuente', 'fountain'] },
    ],
  },
  {
    id: 'objetos',
    label: 'emoji.catObjetos',
    icon: '💡',
    items: [
      { e: '⌚', k: ['relogio pulso hora', 'reloj pulsera hora', 'watch wristwatch time'] },
      { e: '📱', k: ['celular telefone smartphone', 'movil telefono celular smartphone', 'phone mobile smartphone cell'] },
      { e: '💻', k: ['notebook computador laptop', 'portatil ordenador laptop', 'laptop computer notebook'] },
      { e: '🖥️', k: ['computador desktop monitor', 'ordenador sobremesa monitor', 'desktop computer monitor'] },
      { e: '🖨️', k: ['impressora imprimir', 'impresora imprimir', 'printer print'] },
      { e: '⌨️', k: ['teclado', 'teclado', 'keyboard'] },
      { e: '🖱️', k: ['mouse', 'raton', 'computer mouse'] },
      { e: '💽', k: ['disco midia', 'disco soporte', 'minidisc media'] },
      { e: '💾', k: ['disquete salvar', 'disquete guardar', 'floppy disk save'] },
      { e: '💿', k: ['cd disco', 'cd disco', 'cd disc'] },
      { e: '📀', k: ['dvd disco', 'dvd disco', 'dvd disc'] },
      { e: '📷', k: ['camera foto', 'camara foto', 'camera photo'] },
      { e: '📸', k: ['camera flash foto', 'camara flash foto', 'camera flash photo'] },
      { e: '📹', k: ['filmadora video', 'videocamara video', 'video camera camcorder'] },
      { e: '🎥', k: ['camera cinema filme', 'camara cine pelicula', 'movie camera film'] },
      { e: '📽️', k: ['projetor filme', 'proyector pelicula', 'film projector'] },
      { e: '📺', k: ['televisao tv', 'television tele tv', 'television tv'] },
      { e: '📻', k: ['radio', 'radio', 'radio'] },
      { e: '🎙️', k: ['microfone podcast estudio', 'microfono podcast estudio', 'studio microphone podcast'] },
      { e: '⏰', k: ['despertador alarme hora', 'despertador alarma hora', 'alarm clock time'] },
      { e: '⏱️', k: ['cronometro tempo', 'cronometro tiempo', 'stopwatch timer'] },
      { e: '⏳', k: ['ampulheta tempo esperando', 'reloj de arena tiempo esperando', 'hourglass time waiting'] },
      { e: '📡', k: ['antena satelite sinal', 'antena satelite senal', 'satellite antenna signal'] },
      { e: '🔋', k: ['bateria energia', 'bateria energia', 'battery power'] },
      { e: '🔌', k: ['tomada plugue energia', 'enchufe electricidad', 'electric plug power'] },
      { e: '💡', k: ['lampada ideia', 'bombilla idea', 'light bulb idea'] },
      { e: '🔦', k: ['lanterna luz', 'linterna luz', 'flashlight torch light'] },
      { e: '🕯️', k: ['vela', 'vela', 'candle'] },
      { e: '🧯', k: ['extintor incendio', 'extintor incendio', 'fire extinguisher'] },
      { e: '🛢️', k: ['barril petroleo', 'barril petroleo', 'oil drum barrel'] },
      { e: '💸', k: ['dinheiro voando gasto', 'dinero volando gasto', 'money with wings spending'] },
      { e: '💵', k: ['dinheiro nota dolar', 'dinero billete dolar', 'dollar banknote money'] },
      { e: '💰', k: ['saco de dinheiro grana lucro', 'bolsa de dinero pasta ganancia', 'money bag profit cash'] },
      { e: '💳', k: ['cartao de credito pagamento', 'tarjeta de credito pago', 'credit card payment'] },
      { e: '🧾', k: ['recibo nota fiscal fatura', 'recibo factura', 'receipt invoice bill'] },
      { e: '💎', k: ['diamante joia', 'diamante joya', 'gem diamond jewel'] },
      { e: '⚖️', k: ['balanca justica equilibrio', 'balanza justicia equilibrio', 'balance scale justice'] },
      { e: '🔧', k: ['chave inglesa ferramenta conserto', 'llave inglesa herramienta arreglo', 'wrench tool fix'] },
      { e: '🔨', k: ['martelo ferramenta', 'martillo herramienta', 'hammer tool'] },
      { e: '🛠️', k: ['ferramentas manutencao', 'herramientas mantenimiento', 'tools maintenance'] },
      { e: '⚙️', k: ['engrenagem configuracao', 'engranaje configuracion ajustes', 'gear settings config'] },
      { e: '🔩', k: ['parafuso porca', 'tornillo tuerca', 'nut and bolt screw'] },
      { e: '🧰', k: ['caixa de ferramentas', 'caja de herramientas', 'toolbox'] },
      { e: '🧲', k: ['ima atracao', 'iman atraccion', 'magnet attraction'] },
      { e: '🔫', k: ['arma pistola', 'pistola arma', 'gun pistol water pistol'] },
      { e: '💊', k: ['remedio comprimido', 'medicina pastilla', 'pill medicine'] },
      { e: '💉', k: ['seringa vacina injecao', 'jeringa vacuna inyeccion', 'syringe vaccine shot'] },
      { e: '🩺', k: ['estetoscopio medico', 'estetoscopio medico', 'stethoscope doctor'] },
      { e: '🚪', k: ['porta', 'puerta', 'door'] },
      { e: '🛏️', k: ['cama dormir', 'cama dormir', 'bed sleep'] },
      { e: '🛋️', k: ['sofa sala', 'sofa salon', 'couch sofa lounge'] },
      { e: '🚽', k: ['vaso sanitario banheiro', 'vater bano inodoro', 'toilet bathroom'] },
      { e: '🚿', k: ['chuveiro banho', 'ducha bano', 'shower bath'] },
      { e: '🛁', k: ['banheira banho', 'banera bano', 'bathtub bath'] },
      { e: '🧹', k: ['vassoura limpeza', 'escoba limpieza', 'broom cleaning sweep'] },
      { e: '🧺', k: ['cesto roupa', 'cesta ropa', 'basket laundry'] },
      { e: '🧻', k: ['papel higienico', 'papel higienico', 'toilet paper roll'] },
      { e: '🧼', k: ['sabonete limpeza', 'jabon limpieza', 'soap cleaning'] },
      { e: '🔑', k: ['chave acesso senha', 'llave acceso contrasena', 'key access password'] },
      { e: '🔒', k: ['cadeado fechado seguranca', 'candado cerrado seguridad', 'lock closed security'] },
      { e: '🔓', k: ['cadeado aberto', 'candado abierto', 'unlocked open lock'] },
      { e: '📦', k: ['caixa pacote entrega encomenda', 'caja paquete entrega envio', 'package box delivery parcel'] },
      { e: '📫', k: ['caixa de correio', 'buzon', 'mailbox'] },
      { e: '📮', k: ['caixa postal correio', 'buzon correos', 'postbox mail'] },
      { e: '✉️', k: ['envelope email carta', 'sobre correo carta', 'envelope email letter'] },
      { e: '📧', k: ['email arroba mensagem', 'correo arroba mensaje', 'email e-mail message'] },
      { e: '📨', k: ['email recebido mensagem', 'correo recibido mensaje', 'incoming envelope message'] },
      { e: '📩', k: ['email enviado mensagem', 'correo enviado mensaje', 'envelope with arrow sent message'] },
      { e: '📝', k: ['anotacao escrever nota', 'nota escribir apunte', 'memo note writing'] },
      { e: '📄', k: ['documento folha arquivo', 'documento hoja archivo', 'document page file'] },
      { e: '📃', k: ['documento pagina', 'documento pagina', 'page document'] },
      { e: '📑', k: ['marcadores documentos', 'marcadores documentos', 'bookmark tabs documents'] },
      { e: '📊', k: ['grafico barras relatorio dados', 'grafico barras informe datos', 'bar chart report data'] },
      { e: '📈', k: ['grafico subindo crescimento vendas', 'grafico subiendo crecimiento ventas', 'chart increasing growth sales'] },
      { e: '📉', k: ['grafico caindo queda prejuizo', 'grafico bajando caida perdida', 'chart decreasing loss decline'] },
      { e: '📋', k: ['prancheta lista checklist', 'portapapeles lista checklist', 'clipboard list checklist'] },
      { e: '📌', k: ['alfinete fixar', 'chincheta fijar', 'pushpin pin'] },
      { e: '📎', k: ['clipe anexo', 'clip adjunto', 'paperclip attachment'] },
      { e: '📁', k: ['pasta arquivo', 'carpeta archivo', 'folder file'] },
      { e: '📂', k: ['pasta aberta arquivos', 'carpeta abierta archivos', 'open folder files'] },
      { e: '🗂️', k: ['pastas organizacao', 'carpetas organizacion', 'card index dividers organize'] },
      { e: '📅', k: ['calendario data agenda', 'calendario fecha agenda', 'calendar date'] },
      { e: '📆', k: ['calendario agenda', 'calendario agenda', 'calendar tear off'] },
      { e: '🗓️', k: ['calendario mes agenda', 'calendario mes agenda', 'spiral calendar month'] },
      { e: '📇', k: ['fichario contatos', 'fichero contactos', 'card index contacts rolodex'] },
      { e: '🗃️', k: ['arquivo caixa', 'archivo caja', 'file box archive'] },
      { e: '🗑️', k: ['lixeira excluir apagar', 'papelera borrar eliminar', 'wastebasket trash delete'] },
      { e: '📚', k: ['livros estudo', 'libros estudio', 'books study'] },
      { e: '📖', k: ['livro aberto leitura', 'libro abierto lectura', 'open book reading'] },
      { e: '🔖', k: ['marcador de livro', 'marcapaginas', 'bookmark'] },
      { e: '📰', k: ['jornal noticia', 'periodico noticia', 'newspaper news'] },
      { e: '✏️', k: ['lapis escrever', 'lapiz escribir', 'pencil write'] },
      { e: '✒️', k: ['caneta tinta', 'pluma tinta', 'fountain pen ink'] },
      { e: '🖊️', k: ['caneta escrever', 'boligrafo escribir', 'pen write'] },
      { e: '🖍️', k: ['giz de cera', 'cera de colores', 'crayon'] },
      { e: '📏', k: ['regua medida', 'regla medida', 'ruler measure'] },
      { e: '📐', k: ['esquadro medida', 'escuadra medida', 'triangular ruler measure'] },
      { e: '✂️', k: ['tesoura cortar', 'tijeras cortar', 'scissors cut'] },
      { e: '🔍', k: ['lupa busca procurar pesquisa', 'lupa buscar busqueda', 'magnifying glass search find'] },
      { e: '🔎', k: ['lupa busca pesquisa', 'lupa buscar busqueda', 'magnifying glass search'] },
      { e: '🔔', k: ['sino notificacao aviso', 'campana notificacion aviso', 'bell notification alert'] },
      { e: '🔕', k: ['sino cortado silencio mudo', 'campana tachada silencio mudo', 'bell with slash mute silent'] },
      { e: '📢', k: ['megafone anuncio aviso', 'megafono anuncio aviso', 'loudspeaker announcement'] },
      { e: '📣', k: ['megafone torcida anuncio', 'megafono animar anuncio', 'megaphone cheer announce'] },
      { e: '👑', k: ['coroa rei rainha', 'corona rey reina', 'crown king queen'] },
      { e: '👓', k: ['oculos', 'gafas', 'glasses eyeglasses'] },
      { e: '🕶️', k: ['oculos escuros', 'gafas de sol', 'sunglasses'] },
      { e: '👔', k: ['gravata terno trabalho', 'corbata traje trabajo', 'necktie suit work'] },
      { e: '👕', k: ['camiseta roupa', 'camiseta ropa', 't-shirt clothes'] },
      { e: '👗', k: ['vestido roupa', 'vestido ropa', 'dress clothes'] },
      { e: '👠', k: ['salto sapato', 'tacon zapato', 'high heel shoe'] },
      { e: '👟', k: ['tenis sapato', 'zapatilla deportiva zapato', 'sneaker running shoe'] },
      { e: '🎒', k: ['mochila escola', 'mochila escuela', 'backpack school'] },
      { e: '💼', k: ['maleta trabalho negocio', 'maletin trabajo negocio', 'briefcase work business'] },
      { e: '👜', k: ['bolsa', 'bolso', 'handbag purse'] },
      { e: '☂️', k: ['guarda chuva', 'paraguas', 'umbrella'] },
      { e: '🧳', k: ['mala viagem', 'maleta viaje', 'luggage suitcase travel'] },
    ],
  },
  {
    id: 'simbolos',
    label: 'emoji.catSimbolos',
    icon: '❤️',
    items: [
      { e: '✅', k: ['certo confirmado ok verde check', 'correcto confirmado ok verde check', 'check mark done ok green'] },
      { e: '☑️', k: ['marcado check caixa', 'marcado casilla check', 'ballot box check tick'] },
      { e: '✔️', k: ['certo check confirmado', 'correcto check confirmado', 'check mark tick confirmed'] },
      { e: '❌', k: ['errado x cancelar nao', 'mal equis cancelar no', 'cross mark x cancel no'] },
      { e: '❎', k: ['x cancelar', 'equis cancelar', 'cross mark button x'] },
      { e: '⭕', k: ['circulo certo', 'circulo correcto', 'hollow red circle correct'] },
      { e: '🚫', k: ['proibido bloqueado', 'prohibido bloqueado', 'prohibited forbidden blocked'] },
      { e: '⛔', k: ['proibido entrada', 'prohibido entrada', 'no entry forbidden'] },
      { e: '‼️', k: ['exclamacao dupla urgente', 'exclamacion doble urgente', 'double exclamation urgent'] },
      { e: '❗', k: ['exclamacao atencao importante', 'exclamacion atencion importante', 'exclamation mark important attention'] },
      { e: '❓', k: ['interrogacao duvida pergunta', 'interrogacion duda pregunta', 'question mark help ask'] },
      { e: '❔', k: ['interrogacao branca duvida', 'interrogacion blanca duda', 'white question mark doubt'] },
      { e: '⚠️', k: ['atencao aviso cuidado perigo', 'atencion aviso cuidado peligro', 'warning caution danger alert'] },
      { e: '🔞', k: ['proibido menores 18', 'prohibido menores 18', 'no one under eighteen adult'] },
      { e: '📵', k: ['proibido celular', 'prohibido moviles', 'no mobile phones'] },
      { e: '🔇', k: ['mudo sem som', 'mudo sin sonido', 'muted speaker no sound'] },
      { e: '🔊', k: ['som alto volume', 'sonido alto volumen', 'loud speaker volume'] },
      { e: '💬', k: ['balao de fala mensagem conversa', 'bocadillo mensaje conversacion', 'speech balloon message chat'] },
      { e: '💭', k: ['balao de pensamento', 'bocadillo de pensamiento', 'thought balloon thinking'] },
      { e: '🗨️', k: ['balao fala', 'bocadillo habla', 'left speech bubble'] },
      { e: '🗯️', k: ['balao raiva', 'bocadillo enfado', 'anger speech bubble'] },
      { e: '♻️', k: ['reciclagem sustentavel', 'reciclaje sostenible', 'recycling sustainable'] },
      { e: '⚜️', k: ['flor de lis', 'flor de lis', 'fleur de lis'] },
      { e: '🔱', k: ['tridente', 'tridente', 'trident'] },
      { e: '⚛️', k: ['atomo ciencia', 'atomo ciencia', 'atom science'] },
      { e: '🕉️', k: ['om hindu', 'om hindu', 'om hindu'] },
      { e: '✡️', k: ['estrela de davi', 'estrella de david', 'star of david'] },
      { e: '☪️', k: ['islamismo', 'islam', 'star and crescent islam'] },
      { e: '☮️', k: ['paz', 'paz', 'peace symbol'] },
      { e: '✝️', k: ['cruz cristao', 'cruz cristiana', 'latin cross christian'] },
      { e: '☯️', k: ['yin yang equilibrio', 'yin yang equilibrio', 'yin yang balance'] },
      { e: '♈', k: ['aries signo', 'aries signo', 'aries zodiac'] },
      { e: '♉', k: ['touro signo', 'tauro signo', 'taurus zodiac'] },
      { e: '♊', k: ['gemeos signo', 'geminis signo', 'gemini zodiac'] },
      { e: '♋', k: ['cancer signo', 'cancer signo', 'cancer zodiac'] },
      { e: '♌', k: ['leao signo', 'leo signo', 'leo zodiac'] },
      { e: '♍', k: ['virgem signo', 'virgo signo', 'virgo zodiac'] },
      { e: '♎', k: ['libra signo', 'libra signo', 'libra zodiac'] },
      { e: '♏', k: ['escorpiao signo', 'escorpio signo', 'scorpio zodiac'] },
      { e: '♐', k: ['sagitario signo', 'sagitario signo', 'sagittarius zodiac'] },
      { e: '♑', k: ['capricornio signo', 'capricornio signo', 'capricorn zodiac'] },
      { e: '♒', k: ['aquario signo', 'acuario signo', 'aquarius zodiac'] },
      { e: '♓', k: ['peixes signo', 'piscis signo', 'pisces zodiac'] },
      { e: '🆔', k: ['identidade id', 'identidad id', 'id identity'] },
      { e: '🆕', k: ['novo new', 'nuevo new', 'new'] },
      { e: '🆓', k: ['gratis free', 'gratis free', 'free'] },
      { e: '🆗', k: ['ok certo', 'ok correcto', 'ok'] },
      { e: '🆙', k: ['up cima', 'up arriba', 'up'] },
      { e: '🈵', k: ['lotado cheio', 'lleno completo', 'no vacancy full'] },
      { e: '🔴', k: ['circulo vermelho bolinha', 'circulo rojo', 'red circle dot'] },
      { e: '🟠', k: ['circulo laranja', 'circulo naranja', 'orange circle'] },
      { e: '🟡', k: ['circulo amarelo', 'circulo amarillo', 'yellow circle'] },
      { e: '🟢', k: ['circulo verde online', 'circulo verde en linea', 'green circle online'] },
      { e: '🔵', k: ['circulo azul', 'circulo azul', 'blue circle'] },
      { e: '🟣', k: ['circulo roxo', 'circulo morado', 'purple circle'] },
      { e: '⚫', k: ['circulo preto', 'circulo negro', 'black circle'] },
      { e: '⚪', k: ['circulo branco', 'circulo blanco', 'white circle'] },
      { e: '🟥', k: ['quadrado vermelho', 'cuadrado rojo', 'red square'] },
      { e: '🟩', k: ['quadrado verde', 'cuadrado verde', 'green square'] },
      { e: '🟦', k: ['quadrado azul', 'cuadrado azul', 'blue square'] },
      { e: '⬛', k: ['quadrado preto', 'cuadrado negro', 'black square'] },
      { e: '⬜', k: ['quadrado branco', 'cuadrado blanco', 'white square'] },
      { e: '🔶', k: ['losango laranja', 'rombo naranja', 'orange diamond'] },
      { e: '🔷', k: ['losango azul', 'rombo azul', 'blue diamond'] },
      { e: '🔺', k: ['triangulo vermelho cima', 'triangulo rojo arriba', 'red triangle up'] },
      { e: '🔻', k: ['triangulo vermelho baixo', 'triangulo rojo abajo', 'red triangle down'] },
      { e: '➡️', k: ['seta direita', 'flecha derecha', 'right arrow'] },
      { e: '⬅️', k: ['seta esquerda', 'flecha izquierda', 'left arrow'] },
      { e: '⬆️', k: ['seta cima', 'flecha arriba', 'up arrow'] },
      { e: '⬇️', k: ['seta baixo', 'flecha abajo', 'down arrow'] },
      { e: '🔄', k: ['atualizar sincronizar repetir', 'actualizar sincronizar repetir', 'refresh sync repeat arrows'] },
      { e: '🔃', k: ['recarregar girar', 'recargar girar', 'reload rotate arrows'] },
      { e: '▶️', k: ['play tocar', 'play reproducir', 'play button'] },
      { e: '⏸️', k: ['pausa', 'pausa', 'pause button'] },
      { e: '⏹️', k: ['parar stop', 'parar stop', 'stop button'] },
      { e: '⏺️', k: ['gravar rec', 'grabar rec', 'record button rec'] },
      { e: '⏭️', k: ['proxima avancar', 'siguiente avanzar', 'next track skip forward'] },
      { e: '⏮️', k: ['anterior voltar', 'anterior volver', 'previous track skip back'] },
      { e: '🔀', k: ['aleatorio shuffle', 'aleatorio shuffle', 'shuffle random'] },
      { e: '🔁', k: ['repetir loop', 'repetir bucle', 'repeat loop'] },
      { e: '➕', k: ['mais adicionar soma', 'mas anadir suma', 'plus add sum'] },
      { e: '➖', k: ['menos subtrair', 'menos restar', 'minus subtract'] },
      { e: '✖️', k: ['vezes multiplicar', 'por multiplicar', 'multiply times'] },
      { e: '➗', k: ['dividir divisao', 'dividir division', 'divide division'] },
      { e: '💲', k: ['cifrao dinheiro dolar', 'signo dolar dinero', 'dollar sign money'] },
      { e: '™️', k: ['marca registrada', 'marca registrada', 'trade mark tm'] },
      { e: '©️', k: ['copyright direitos', 'copyright derechos', 'copyright'] },
      { e: '®️', k: ['marca registrada', 'marca registrada', 'registered trademark'] },
      { e: '#️⃣', k: ['hashtag cerquilha', 'almohadilla hashtag', 'hashtag hash pound'] },
      { e: '*️⃣', k: ['asterisco', 'asterisco', 'asterisk star key'] },
      { e: '0️⃣', k: ['zero numero', 'cero numero', 'zero number'] },
      { e: '1️⃣', k: ['um numero', 'uno numero', 'one number'] },
      { e: '2️⃣', k: ['dois numero', 'dos numero', 'two number'] },
      { e: '3️⃣', k: ['tres numero', 'tres numero', 'three number'] },
      { e: '4️⃣', k: ['quatro numero', 'cuatro numero', 'four number'] },
      { e: '5️⃣', k: ['cinco numero', 'cinco numero', 'five number'] },
      { e: '6️⃣', k: ['seis numero', 'seis numero', 'six number'] },
      { e: '7️⃣', k: ['sete numero', 'siete numero', 'seven number'] },
      { e: '8️⃣', k: ['oito numero', 'ocho numero', 'eight number'] },
      { e: '9️⃣', k: ['nove numero', 'nueve numero', 'nine number'] },
      { e: '🔟', k: ['dez numero', 'diez numero', 'ten number'] },
    ],
  },
  {
    id: 'bandeiras',
    label: 'emoji.catBandeiras',
    icon: '🏳️',
    items: [
      { e: '🏳️', k: ['bandeira branca rendicao', 'bandera blanca rendicion', 'white flag surrender'] },
      { e: '🏴', k: ['bandeira preta', 'bandera negra', 'black flag'] },
      { e: '🏁', k: ['bandeira quadriculada chegada fim', 'bandera a cuadros meta fin', 'chequered flag finish line'] },
      { e: '🚩', k: ['bandeira vermelha alerta', 'bandera roja alerta', 'triangular flag red alert'] },
      { e: '🏳️‍🌈', k: ['bandeira arco iris lgbt orgulho', 'bandera arcoiris lgbt orgullo', 'rainbow flag lgbt pride'] },
      { e: '🇧🇷', k: ['brasil bandeira', 'brasil bandera', 'brazil flag'] },
      { e: '🇵🇹', k: ['portugal bandeira', 'portugal bandera', 'portugal flag'] },
      { e: '🇺🇸', k: ['estados unidos eua bandeira', 'estados unidos eeuu bandera', 'united states usa flag'] },
      { e: '🇦🇷', k: ['argentina bandeira', 'argentina bandera', 'argentina flag'] },
      { e: '🇺🇾', k: ['uruguai bandeira', 'uruguay bandera', 'uruguay flag'] },
      { e: '🇨🇱', k: ['chile bandeira', 'chile bandera', 'chile flag'] },
      { e: '🇵🇾', k: ['paraguai bandeira', 'paraguay bandera', 'paraguay flag'] },
      { e: '🇧🇴', k: ['bolivia bandeira', 'bolivia bandera', 'bolivia flag'] },
      { e: '🇨🇴', k: ['colombia bandeira', 'colombia bandera', 'colombia flag'] },
      { e: '🇵🇪', k: ['peru bandeira', 'peru bandera', 'peru flag'] },
      { e: '🇲🇽', k: ['mexico bandeira', 'mexico bandera', 'mexico flag'] },
      { e: '🇨🇦', k: ['canada bandeira', 'canada bandera', 'canada flag'] },
      { e: '🇪🇸', k: ['espanha bandeira', 'espana bandera', 'spain flag'] },
      { e: '🇫🇷', k: ['franca bandeira', 'francia bandera', 'france flag'] },
      { e: '🇮🇹', k: ['italia bandeira', 'italia bandera', 'italy flag'] },
      { e: '🇩🇪', k: ['alemanha bandeira', 'alemania bandera', 'germany flag'] },
      { e: '🇬🇧', k: ['reino unido inglaterra bandeira', 'reino unido inglaterra bandera', 'united kingdom england britain flag'] },
      { e: '🇮🇪', k: ['irlanda bandeira', 'irlanda bandera', 'ireland flag'] },
      { e: '🇳🇱', k: ['holanda paises baixos bandeira', 'holanda paises bajos bandera', 'netherlands holland flag'] },
      { e: '🇨🇭', k: ['suica bandeira', 'suiza bandera', 'switzerland flag'] },
      { e: '🇸🇪', k: ['suecia bandeira', 'suecia bandera', 'sweden flag'] },
      { e: '🇳🇴', k: ['noruega bandeira', 'noruega bandera', 'norway flag'] },
      { e: '🇷🇺', k: ['russia bandeira', 'rusia bandera', 'russia flag'] },
      { e: '🇨🇳', k: ['china bandeira', 'china bandera', 'china flag'] },
      { e: '🇯🇵', k: ['japao bandeira', 'japon bandera', 'japan flag'] },
      { e: '🇰🇷', k: ['coreia do sul bandeira', 'corea del sur bandera', 'south korea flag'] },
      { e: '🇮🇳', k: ['india bandeira', 'india bandera', 'india flag'] },
      { e: '🇦🇺', k: ['australia bandeira', 'australia bandera', 'australia flag'] },
      { e: '🇿🇦', k: ['africa do sul bandeira', 'sudafrica bandera', 'south africa flag'] },
      { e: '🇦🇴', k: ['angola bandeira', 'angola bandera', 'angola flag'] },
      { e: '🇲🇿', k: ['mocambique bandeira', 'mozambique bandera', 'mozambique flag'] },
    ],
  },
]

/** Sem acento e em minúsculas — usado nos dois lados da busca. */
function fold(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

/**
 * Índice de busca montado uma vez: emoji + palavras-chave dos TRÊS idiomas, já
 * normalizadas, mais o nome da categoria também nos três — "smileys", "sonrisas" e
 * "carinhas" levam todos à mesma aba.
 *
 * Antes daqui entrava `c.label`, que hoje é a CHAVE do catálogo: a busca casava com
 * 'emoji.catSmileys', o nome interno, e nunca com o nome que a pessoa lê.
 *
 * Por unir os três, ele pode continuar sendo constante de módulo sem cair na armadilha
 * de sempre: não há idioma ativo dentro dele para congelar.
 */
const SEARCH_INDEX: { item: EmojiEntry; hay: string }[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.items.map((item) => ({ item, hay: fold(`${TRADUCOES[c.label].join(' ')} ${item.k.join(' ')}`) })),
)

/** Busca por palavra-chave (acento-insensível). Query vazia devolve lista vazia. */
export function searchEmojis(query: string, limit = 120): EmojiEntry[] {
  const q = fold(query.trim())
  if (!q) return []
  const terms = q.split(/\s+/)
  const out: EmojiEntry[] = []
  for (const { item, hay } of SEARCH_INDEX) {
    if (terms.every((t) => hay.includes(t))) out.push(item)
    if (out.length >= limit) break
  }
  return out
}

/**
 * A primeira palavra-chave NO IDIOMA DA TELA — é o `title` do botão na grade,
 * o balãozinho que diz o que é aquele desenho de 23px.
 *
 * Aqui, ao contrário da busca, mostrar os três idiomas de uma vez não ajudaria
 * ninguém: "sorriso sonrisa smile" não é tradução, é ruído.
 */
export function rotuloEmoji(item: EmojiEntry): string {
  const palavras = item.k[indiceIdioma()] || item.k[0]
  return palavras.split(' ')[0] ?? ''
}

/** Todos os emojis do catálogo, indexados pelo caractere — resolve os "frequentes" salvos. */
const BY_CHAR = new Map(EMOJI_CATEGORIES.flatMap((c) => c.items).map((i) => [i.e, i]))

export function emojiByChar(char: string): EmojiEntry | undefined {
  return BY_CHAR.get(char)
}
