// Catálogo de emojis do seletor (src/components/common/EmojiPicker.tsx).
//
// As categorias e a ordem seguem o teclado de emoji do iPhone. O DESENHO de cada emoji vem
// da fonte do sistema — em iPhone/Mac já é a arte da Apple, no Windows/Android é a da própria
// plataforma. Servir a arte da Apple em qualquer aparelho exigiria baixar as imagens de uma
// CDN externa, coisa que este app não faz.
//
// `k` são as palavras-chave da busca, em PT-BR e com sinônimos comuns. A busca normaliza
// acentos dos dois lados (ver `searchEmojis`), então "coracao" acha "coração".

export interface EmojiEntry {
  /** O caractere em si. */
  e: string
  /** Palavras-chave da busca, separadas por espaço. */
  k: string
}

export interface EmojiCategory {
  id: string
  /** Rótulo exibido acima da grade. */
  label: string
  /** Emoji usado como ícone da aba (mesma ideia das abas do iPhone). */
  icon: string
  items: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys e pessoas',
    icon: '😀',
    items: [
      { e: '😀', k: 'sorriso feliz cara alegre' },
      { e: '😃', k: 'sorriso feliz alegre boca aberta' },
      { e: '😄', k: 'sorriso feliz alegre olhos' },
      { e: '😁', k: 'sorriso radiante feliz dentes' },
      { e: '😆', k: 'risada gargalhada feliz' },
      { e: '😅', k: 'risada suor alivio nervoso' },
      { e: '🤣', k: 'risada rolando chao gargalhada rindo' },
      { e: '😂', k: 'risada chorando de rir lagrima gargalhada' },
      { e: '🙂', k: 'sorriso leve simpatico' },
      { e: '🙃', k: 'cabeca para baixo ironia sarcasmo' },
      { e: '😉', k: 'piscada flerte brincadeira' },
      { e: '😊', k: 'sorriso timido feliz corado' },
      { e: '😇', k: 'anjo santo auréola inocente' },
      { e: '🥰', k: 'apaixonado amor coracoes carinho' },
      { e: '😍', k: 'apaixonado olhos de coracao amor' },
      { e: '🤩', k: 'estrelas deslumbrado uau incrivel' },
      { e: '😘', k: 'beijo mandando beijo amor' },
      { e: '😗', k: 'beijo bico' },
      { e: '😚', k: 'beijo olhos fechados' },
      { e: '😙', k: 'beijo sorriso' },
      { e: '😋', k: 'delicia lambendo gostoso saboroso' },
      { e: '😛', k: 'lingua brincadeira' },
      { e: '😜', k: 'lingua piscada brincalhao' },
      { e: '🤪', k: 'doido maluco louco' },
      { e: '😝', k: 'lingua olhos fechados brincadeira' },
      { e: '🤑', k: 'dinheiro cifrao rico ganancia' },
      { e: '🤗', k: 'abraco acolhimento carinho' },
      { e: '🤭', k: 'ops boca tapada risadinha' },
      { e: '🤫', k: 'silencio shh segredo' },
      { e: '🤔', k: 'pensando duvida hmm reflexao' },
      { e: '🤐', k: 'boca fechada ziper calado' },
      { e: '🤨', k: 'sobrancelha desconfiado duvida' },
      { e: '😐', k: 'neutro sem expressao' },
      { e: '😑', k: 'sem expressao entediado' },
      { e: '😶', k: 'sem boca mudo calado' },
      { e: '😏', k: 'sorriso malicioso safado convencido' },
      { e: '😒', k: 'chateado sem gracao contrariado' },
      { e: '🙄', k: 'revirando os olhos tedio ironia' },
      { e: '😬', k: 'careta constrangido nervoso' },
      { e: '🤥', k: 'mentira nariz pinoquio' },
      { e: '😌', k: 'aliviado calmo tranquilo' },
      { e: '😔', k: 'triste pensativo desanimado' },
      { e: '😪', k: 'sono cansado dormindo' },
      { e: '🤤', k: 'babando desejo fome' },
      { e: '😴', k: 'dormindo sono zzz' },
      { e: '😷', k: 'mascara doente gripe' },
      { e: '🤒', k: 'doente febre termometro' },
      { e: '🤕', k: 'machucado curativo ferido' },
      { e: '🤢', k: 'enjoado nojo verde' },
      { e: '🤮', k: 'vomitando enjoo nojo' },
      { e: '🤧', k: 'espirro resfriado gripe' },
      { e: '🥵', k: 'calor quente suando' },
      { e: '🥶', k: 'frio congelando gelo' },
      { e: '🥴', k: 'tonto bebado zonzo' },
      { e: '😵', k: 'tonto atordoado desmaio' },
      { e: '🤯', k: 'explodindo mente chocado uau' },
      { e: '🤠', k: 'cowboy chapeu caubói' },
      { e: '🥳', k: 'festa comemoracao aniversario' },
      { e: '😎', k: 'oculos escuros estiloso legal' },
      { e: '🤓', k: 'nerd geek estudioso oculos' },
      { e: '🧐', k: 'monoculo analisando curioso' },
      { e: '😕', k: 'confuso incerto' },
      { e: '😟', k: 'preocupado aflito' },
      { e: '🙁', k: 'triste leve descontente' },
      { e: '😮', k: 'surpreso boca aberta uau' },
      { e: '😯', k: 'surpreso espantado' },
      { e: '😲', k: 'chocado assombrado surpresa' },
      { e: '😳', k: 'envergonhado corado surpreso' },
      { e: '🥺', k: 'implorando carinha pidao fofo' },
      { e: '😦', k: 'assustado boca aberta' },
      { e: '😧', k: 'angustiado aflito' },
      { e: '😨', k: 'medo assustado' },
      { e: '😰', k: 'ansioso suor medo' },
      { e: '😥', k: 'triste aliviado decepcionado' },
      { e: '😢', k: 'chorando triste lagrima' },
      { e: '😭', k: 'chorando muito triste soluco' },
      { e: '😱', k: 'grito medo panico susto' },
      { e: '😖', k: 'confuso frustrado' },
      { e: '😣', k: 'perseverando esforco dor' },
      { e: '😞', k: 'decepcionado triste' },
      { e: '😓', k: 'suando triste cansado' },
      { e: '😩', k: 'cansado exausto chateado' },
      { e: '😫', k: 'exausto cansado desesperado' },
      { e: '🥱', k: 'bocejo sono tedio' },
      { e: '😤', k: 'bufando raiva orgulho' },
      { e: '😡', k: 'raiva bravo furioso vermelho' },
      { e: '😠', k: 'bravo irritado raiva' },
      { e: '🤬', k: 'xingando palavrao raiva' },
      { e: '😈', k: 'diabo travesso safado' },
      { e: '👿', k: 'diabo bravo raiva' },
      { e: '💀', k: 'caveira morte cranio' },
      { e: '💩', k: 'coco merda bosta' },
      { e: '🤡', k: 'palhaco circo' },
      { e: '👻', k: 'fantasma assombracao halloween' },
      { e: '👽', k: 'alien et extraterrestre' },
      { e: '🤖', k: 'robo bot inteligencia artificial' },
      { e: '🎃', k: 'abobora halloween' },
      { e: '😺', k: 'gato sorrindo' },
      { e: '😻', k: 'gato apaixonado coracao' },
      { e: '🙈', k: 'macaco nao vejo vergonha' },
      { e: '🙉', k: 'macaco nao ouco' },
      { e: '🙊', k: 'macaco nao falo segredo' },
      { e: '❤️', k: 'coracao amor vermelho' },
      { e: '🧡', k: 'coracao laranja amor' },
      { e: '💛', k: 'coracao amarelo amor amizade' },
      { e: '💚', k: 'coracao verde amor' },
      { e: '💙', k: 'coracao azul amor' },
      { e: '💜', k: 'coracao roxo amor' },
      { e: '🖤', k: 'coracao preto' },
      { e: '🤍', k: 'coracao branco' },
      { e: '🤎', k: 'coracao marrom' },
      { e: '💔', k: 'coracao partido termino tristeza' },
      { e: '❣️', k: 'coracao exclamacao amor' },
      { e: '💕', k: 'dois coracoes amor' },
      { e: '💞', k: 'coracoes girando amor' },
      { e: '💓', k: 'coracao batendo amor' },
      { e: '💗', k: 'coracao crescendo amor' },
      { e: '💖', k: 'coracao brilhando amor' },
      { e: '💘', k: 'coracao flecha cupido paixao' },
      { e: '💝', k: 'coracao presente laco' },
      { e: '💯', k: 'cem nota maxima perfeito' },
      { e: '💢', k: 'raiva irritacao' },
      { e: '💥', k: 'explosao boom' },
      { e: '💫', k: 'tontura estrelas' },
      { e: '💦', k: 'gotas suor agua' },
      { e: '💨', k: 'vento correndo fumaca' },
      { e: '👋', k: 'tchau oi aceno mao' },
      { e: '🤚', k: 'mao levantada' },
      { e: '✋', k: 'mao parada stop' },
      { e: '🖐️', k: 'mao dedos abertos' },
      { e: '👌', k: 'ok joia certo perfeito' },
      { e: '🤌', k: 'mao italiana gesto' },
      { e: '🤏', k: 'pouco pequeno pitada' },
      { e: '✌️', k: 'paz vitoria dois dedos' },
      { e: '🤞', k: 'dedos cruzados sorte torcendo' },
      { e: '🤟', k: 'amor rock mao' },
      { e: '🤘', k: 'rock chifrinho metal' },
      { e: '🤙', k: 'me liga shaka' },
      { e: '👈', k: 'apontando esquerda' },
      { e: '👉', k: 'apontando direita' },
      { e: '👆', k: 'apontando cima' },
      { e: '👇', k: 'apontando baixo' },
      { e: '☝️', k: 'dedo indicador cima atencao' },
      { e: '👍', k: 'joia positivo curtir like legal' },
      { e: '👎', k: 'negativo nao gostei deslike' },
      { e: '✊', k: 'punho forca luta' },
      { e: '👊', k: 'soco punho toca aqui' },
      { e: '🤛', k: 'punho esquerda' },
      { e: '🤜', k: 'punho direita' },
      { e: '👏', k: 'palmas aplauso parabens' },
      { e: '🙌', k: 'maos ao alto comemorar aleluia' },
      { e: '👐', k: 'maos abertas abraco' },
      { e: '🤲', k: 'maos juntas pedido oracao' },
      { e: '🤝', k: 'aperto de mao acordo negocio parceria' },
      { e: '🙏', k: 'oracao obrigado por favor reza' },
      { e: '✍️', k: 'escrevendo assinatura' },
      { e: '💅', k: 'unha esmalte' },
      { e: '💪', k: 'forca musculo biceps academia' },
      { e: '🦵', k: 'perna' },
      { e: '👀', k: 'olhos olhando atencao' },
      { e: '👁️', k: 'olho' },
      { e: '👄', k: 'boca labios' },
      { e: '👅', k: 'lingua' },
      { e: '👶', k: 'bebe crianca' },
      { e: '🧒', k: 'crianca' },
      { e: '👦', k: 'menino garoto' },
      { e: '👧', k: 'menina garota' },
      { e: '🧑', k: 'pessoa adulto' },
      { e: '👨', k: 'homem' },
      { e: '👩', k: 'mulher' },
      { e: '🧓', k: 'idoso pessoa mais velha' },
      { e: '👴', k: 'senhor idoso vovo' },
      { e: '👵', k: 'senhora idosa vovo' },
      { e: '👮', k: 'policial' },
      { e: '👷', k: 'operario obra construcao' },
      { e: '💂', k: 'guarda' },
      { e: '🕵️', k: 'detetive espiao' },
      { e: '👩‍⚕️', k: 'medica enfermeira saude' },
      { e: '👨‍⚕️', k: 'medico enfermeiro saude' },
      { e: '👩‍🏫', k: 'professora escola' },
      { e: '👨‍🏫', k: 'professor escola' },
      { e: '👩‍💻', k: 'programadora tecnologia trabalho' },
      { e: '👨‍💻', k: 'programador tecnologia trabalho' },
      { e: '👩‍💼', k: 'executiva escritorio trabalho' },
      { e: '👨‍💼', k: 'executivo escritorio trabalho' },
      { e: '🤵', k: 'terno smoking casamento' },
      { e: '👰', k: 'noiva casamento veu' },
      { e: '🤰', k: 'gravida gestante' },
      { e: '🎅', k: 'papai noel natal' },
      { e: '🦸', k: 'super heroi' },
      { e: '🧙', k: 'mago bruxo magia' },
      { e: '🧚', k: 'fada magia' },
      { e: '💁', k: 'informacao atendente ombro' },
      { e: '🙋', k: 'levantando a mao presente eu' },
      { e: '🙇', k: 'reverencia desculpa respeito' },
      { e: '🤦', k: 'facepalm mao na testa descrenca' },
      { e: '🤷', k: 'ombros sei la tanto faz' },
      { e: '🙅', k: 'nao proibido negando' },
      { e: '🙆', k: 'ok certo positivo' },
      { e: '💇', k: 'corte de cabelo salao' },
      { e: '🚶', k: 'andando caminhando pedestre' },
      { e: '🏃', k: 'correndo corrida pressa' },
      { e: '💃', k: 'danca mulher festa' },
      { e: '🕺', k: 'danca homem festa' },
      { e: '👯', k: 'dupla festa orelhas de coelho' },
      { e: '👪', k: 'familia' },
      { e: '👫', k: 'casal de maos dadas' },
      { e: '💑', k: 'casal apaixonado' },
      { e: '💏', k: 'casal beijando' },
    ],
  },
  {
    id: 'natureza',
    label: 'Animais e natureza',
    icon: '🐻',
    items: [
      { e: '🐶', k: 'cachorro cao dog' },
      { e: '🐱', k: 'gato gata cat' },
      { e: '🐭', k: 'rato camundongo' },
      { e: '🐹', k: 'hamster' },
      { e: '🐰', k: 'coelho' },
      { e: '🦊', k: 'raposa' },
      { e: '🐻', k: 'urso' },
      { e: '🐼', k: 'panda' },
      { e: '🐨', k: 'coala' },
      { e: '🐯', k: 'tigre' },
      { e: '🦁', k: 'leao' },
      { e: '🐮', k: 'vaca boi' },
      { e: '🐷', k: 'porco' },
      { e: '🐸', k: 'sapo ra' },
      { e: '🐵', k: 'macaco' },
      { e: '🐔', k: 'galinha' },
      { e: '🐧', k: 'pinguim' },
      { e: '🐦', k: 'passaro ave' },
      { e: '🐤', k: 'pintinho' },
      { e: '🦆', k: 'pato' },
      { e: '🦅', k: 'aguia' },
      { e: '🦉', k: 'coruja' },
      { e: '🦇', k: 'morcego' },
      { e: '🐺', k: 'lobo' },
      { e: '🐗', k: 'javali' },
      { e: '🐴', k: 'cavalo' },
      { e: '🦄', k: 'unicornio magia' },
      { e: '🐝', k: 'abelha mel' },
      { e: '🐛', k: 'lagarta bug inseto' },
      { e: '🦋', k: 'borboleta' },
      { e: '🐌', k: 'caracol lesma devagar' },
      { e: '🐞', k: 'joaninha' },
      { e: '🐜', k: 'formiga' },
      { e: '🕷️', k: 'aranha' },
      { e: '🦂', k: 'escorpiao' },
      { e: '🐢', k: 'tartaruga' },
      { e: '🐍', k: 'cobra serpente' },
      { e: '🦎', k: 'lagarto' },
      { e: '🐙', k: 'polvo' },
      { e: '🦐', k: 'camarao' },
      { e: '🦀', k: 'caranguejo' },
      { e: '🐠', k: 'peixe tropical' },
      { e: '🐟', k: 'peixe' },
      { e: '🐬', k: 'golfinho' },
      { e: '🐳', k: 'baleia' },
      { e: '🦈', k: 'tubarao' },
      { e: '🐊', k: 'crocodilo jacare' },
      { e: '🐘', k: 'elefante' },
      { e: '🦏', k: 'rinoceronte' },
      { e: '🐫', k: 'camelo' },
      { e: '🦒', k: 'girafa' },
      { e: '🐆', k: 'onca leopardo' },
      { e: '🐄', k: 'vaca gado' },
      { e: '🐖', k: 'porco suino' },
      { e: '🐑', k: 'ovelha' },
      { e: '🐐', k: 'cabra bode' },
      { e: '🐓', k: 'galo' },
      { e: '🦃', k: 'peru' },
      { e: '🕊️', k: 'pomba paz' },
      { e: '🐕', k: 'cachorro cao' },
      { e: '🐈', k: 'gato' },
      { e: '🐇', k: 'coelho' },
      { e: '🐁', k: 'rato' },
      { e: '🌵', k: 'cacto deserto' },
      { e: '🌲', k: 'pinheiro arvore' },
      { e: '🌳', k: 'arvore' },
      { e: '🌴', k: 'coqueiro palmeira praia' },
      { e: '🌱', k: 'muda broto crescimento' },
      { e: '🌿', k: 'erva folha planta' },
      { e: '☘️', k: 'trevo sorte' },
      { e: '🍀', k: 'trevo quatro folhas sorte' },
      { e: '🍁', k: 'folha outono' },
      { e: '🍂', k: 'folhas caidas outono' },
      { e: '🍃', k: 'folhas vento' },
      { e: '🌷', k: 'tulipa flor' },
      { e: '🌹', k: 'rosa flor amor' },
      { e: '🥀', k: 'flor murcha' },
      { e: '🌺', k: 'hibisco flor' },
      { e: '🌸', k: 'flor de cerejeira sakura' },
      { e: '🌼', k: 'margarida flor' },
      { e: '🌻', k: 'girassol flor' },
      { e: '🌞', k: 'sol sorrindo' },
      { e: '🌝', k: 'lua cheia rosto' },
      { e: '🌚', k: 'lua nova rosto' },
      { e: '🌙', k: 'lua noite' },
      { e: '⭐', k: 'estrela' },
      { e: '🌟', k: 'estrela brilhante' },
      { e: '✨', k: 'brilho estrelas magia novo' },
      { e: '⚡', k: 'raio energia rapido' },
      { e: '🔥', k: 'fogo chama incrivel top' },
      { e: '🌈', k: 'arco iris' },
      { e: '☀️', k: 'sol tempo bom' },
      { e: '⛅', k: 'sol e nuvem tempo' },
      { e: '☁️', k: 'nuvem nublado' },
      { e: '🌧️', k: 'chuva' },
      { e: '⛈️', k: 'tempestade trovao' },
      { e: '❄️', k: 'neve floco frio' },
      { e: '☃️', k: 'boneco de neve' },
      { e: '💧', k: 'gota agua' },
      { e: '🌊', k: 'onda mar praia' },
      { e: '🌍', k: 'terra mundo planeta' },
      { e: '🌎', k: 'terra americas mundo' },
      { e: '🌏', k: 'terra asia mundo' },
      { e: '🌪️', k: 'tornado furacao' },
      { e: '🌫️', k: 'neblina nevoeiro' },
    ],
  },
  {
    id: 'comida',
    label: 'Comidas e bebidas',
    icon: '🍔',
    items: [
      { e: '🍎', k: 'maca fruta' },
      { e: '🍏', k: 'maca verde fruta' },
      { e: '🍐', k: 'pera fruta' },
      { e: '🍊', k: 'laranja fruta' },
      { e: '🍋', k: 'limao fruta' },
      { e: '🍌', k: 'banana fruta' },
      { e: '🍉', k: 'melancia fruta' },
      { e: '🍇', k: 'uva fruta' },
      { e: '🍓', k: 'morango fruta' },
      { e: '🫐', k: 'mirtilo fruta' },
      { e: '🍈', k: 'melao fruta' },
      { e: '🍒', k: 'cereja fruta' },
      { e: '🍑', k: 'pessego fruta bumbum' },
      { e: '🥭', k: 'manga fruta' },
      { e: '🍍', k: 'abacaxi fruta' },
      { e: '🥥', k: 'coco fruta' },
      { e: '🥝', k: 'kiwi fruta' },
      { e: '🍅', k: 'tomate' },
      { e: '🥑', k: 'abacate' },
      { e: '🍆', k: 'berinjela' },
      { e: '🥔', k: 'batata' },
      { e: '🥕', k: 'cenoura' },
      { e: '🌽', k: 'milho' },
      { e: '🌶️', k: 'pimenta apimentado' },
      { e: '🥒', k: 'pepino' },
      { e: '🥬', k: 'alface verdura' },
      { e: '🥦', k: 'brocolis' },
      { e: '🧄', k: 'alho' },
      { e: '🧅', k: 'cebola' },
      { e: '🍄', k: 'cogumelo' },
      { e: '🥜', k: 'amendoim' },
      { e: '🌰', k: 'castanha' },
      { e: '🍞', k: 'pao' },
      { e: '🥐', k: 'croissant' },
      { e: '🥖', k: 'baguete pao' },
      { e: '🥨', k: 'pretzel' },
      { e: '🧀', k: 'queijo' },
      { e: '🥚', k: 'ovo' },
      { e: '🍳', k: 'ovo frito cafe da manha' },
      { e: '🥞', k: 'panqueca' },
      { e: '🧇', k: 'waffle' },
      { e: '🥓', k: 'bacon' },
      { e: '🍗', k: 'frango coxa' },
      { e: '🍖', k: 'carne osso churrasco' },
      { e: '🌭', k: 'cachorro quente hot dog' },
      { e: '🍔', k: 'hamburguer lanche' },
      { e: '🍟', k: 'batata frita' },
      { e: '🍕', k: 'pizza' },
      { e: '🥪', k: 'sanduiche' },
      { e: '🌮', k: 'taco' },
      { e: '🌯', k: 'burrito wrap' },
      { e: '🥗', k: 'salada' },
      { e: '🥘', k: 'panela comida' },
      { e: '🍝', k: 'macarrao espaguete massa' },
      { e: '🍜', k: 'lamen sopa macarrao' },
      { e: '🍲', k: 'sopa caldo' },
      { e: '🍛', k: 'arroz curry' },
      { e: '🍣', k: 'sushi' },
      { e: '🍤', k: 'camarao frito tempura' },
      { e: '🥟', k: 'guioza pastel' },
      { e: '🍚', k: 'arroz' },
      { e: '🍱', k: 'marmita bento' },
      { e: '🥩', k: 'carne bife picanha' },
      { e: '🍦', k: 'sorvete casquinha' },
      { e: '🍧', k: 'raspadinha gelo' },
      { e: '🍨', k: 'sorvete taca' },
      { e: '🍩', k: 'rosquinha donut' },
      { e: '🍪', k: 'biscoito cookie' },
      { e: '🎂', k: 'bolo aniversario' },
      { e: '🍰', k: 'fatia de bolo' },
      { e: '🧁', k: 'cupcake' },
      { e: '🥧', k: 'torta' },
      { e: '🍫', k: 'chocolate' },
      { e: '🍬', k: 'bala doce' },
      { e: '🍭', k: 'pirulito' },
      { e: '🍮', k: 'pudim' },
      { e: '🍯', k: 'mel' },
      { e: '🍿', k: 'pipoca cinema' },
      { e: '🧂', k: 'sal' },
      { e: '🥛', k: 'leite copo' },
      { e: '☕', k: 'cafe cafezinho quente' },
      { e: '🍵', k: 'cha' },
      { e: '🧃', k: 'suco caixinha' },
      { e: '🥤', k: 'refrigerante copo' },
      { e: '🍺', k: 'cerveja chopp' },
      { e: '🍻', k: 'cervejas brinde' },
      { e: '🥂', k: 'brinde tacas comemoracao' },
      { e: '🍷', k: 'vinho taca' },
      { e: '🥃', k: 'whisky dose' },
      { e: '🍸', k: 'drink coquetel martini' },
      { e: '🍹', k: 'drink tropical' },
      { e: '🍾', k: 'champanhe comemoracao' },
      { e: '🧉', k: 'chimarrao mate' },
      { e: '🥄', k: 'colher' },
      { e: '🍴', k: 'garfo e faca comer' },
      { e: '🍽️', k: 'prato talheres jantar' },
    ],
  },
  {
    id: 'atividades',
    label: 'Atividades',
    icon: '⚽',
    items: [
      { e: '⚽', k: 'futebol bola' },
      { e: '🏀', k: 'basquete bola' },
      { e: '🏈', k: 'futebol americano' },
      { e: '⚾', k: 'beisebol' },
      { e: '🥎', k: 'softbol' },
      { e: '🎾', k: 'tenis' },
      { e: '🏐', k: 'volei' },
      { e: '🏉', k: 'rugby' },
      { e: '🎱', k: 'sinuca bilhar' },
      { e: '🏓', k: 'ping pong tenis de mesa' },
      { e: '🏸', k: 'badminton' },
      { e: '🥅', k: 'gol trave' },
      { e: '🏒', k: 'hoquei' },
      { e: '🏑', k: 'hoquei grama' },
      { e: '🥍', k: 'lacrosse' },
      { e: '🏏', k: 'criquete' },
      { e: '⛳', k: 'golfe' },
      { e: '🏹', k: 'arco e flecha' },
      { e: '🎣', k: 'pesca' },
      { e: '🤿', k: 'mergulho' },
      { e: '🥊', k: 'boxe luva' },
      { e: '🥋', k: 'artes marciais judo karate' },
      { e: '🎽', k: 'corrida camiseta' },
      { e: '🛹', k: 'skate' },
      { e: '🛼', k: 'patins' },
      { e: '⛸️', k: 'patinacao no gelo' },
      { e: '🎿', k: 'esqui' },
      { e: '🏂', k: 'snowboard' },
      { e: '🏋️', k: 'academia musculacao peso' },
      { e: '🤸', k: 'ginastica cambalhota' },
      { e: '🤼', k: 'luta' },
      { e: '🤽', k: 'polo aquatico' },
      { e: '🤾', k: 'handebol' },
      { e: '🧘', k: 'ioga meditacao calma' },
      { e: '🏊', k: 'natacao nadando' },
      { e: '🚴', k: 'ciclismo bicicleta' },
      { e: '🚵', k: 'mountain bike' },
      { e: '🏆', k: 'trofeu vitoria campeao premio' },
      { e: '🥇', k: 'medalha ouro primeiro' },
      { e: '🥈', k: 'medalha prata segundo' },
      { e: '🥉', k: 'medalha bronze terceiro' },
      { e: '🏅', k: 'medalha premio' },
      { e: '🎖️', k: 'medalha militar honra' },
      { e: '🎯', k: 'alvo meta objetivo' },
      { e: '🎲', k: 'dado sorte jogo' },
      { e: '🎰', k: 'caca niquel sorte' },
      { e: '🎳', k: 'boliche' },
      { e: '🎮', k: 'videogame controle jogo' },
      { e: '🕹️', k: 'joystick arcade' },
      { e: '🧩', k: 'quebra cabeca peca' },
      { e: '🎨', k: 'arte pintura paleta' },
      { e: '🎭', k: 'teatro mascaras' },
      { e: '🎤', k: 'microfone cantar karaoke' },
      { e: '🎧', k: 'fone de ouvido musica' },
      { e: '🎼', k: 'partitura musica' },
      { e: '🎵', k: 'nota musical musica' },
      { e: '🎶', k: 'notas musicais musica' },
      { e: '🎹', k: 'piano teclado' },
      { e: '🥁', k: 'bateria tambor' },
      { e: '🎸', k: 'guitarra violao' },
      { e: '🎺', k: 'trompete' },
      { e: '🎻', k: 'violino' },
      { e: '🪗', k: 'acordeao sanfona' },
      { e: '🎬', k: 'cinema claquete filme' },
      { e: '🎪', k: 'circo' },
      { e: '🎉', k: 'festa comemoracao parabens' },
      { e: '🎊', k: 'confete festa' },
      { e: '🎈', k: 'balao festa' },
      { e: '🎁', k: 'presente aniversario' },
      { e: '🎀', k: 'laco fita' },
      { e: '🎄', k: 'arvore de natal' },
      { e: '🎇', k: 'fogos de artificio' },
      { e: '🎆', k: 'fogos de artificio festa' },
      { e: '🧨', k: 'dinamite explosivo' },
      { e: '🪅', k: 'pinhata festa' },
    ],
  },
  {
    id: 'viagens',
    label: 'Viagens e lugares',
    icon: '🚗',
    items: [
      { e: '🚗', k: 'carro automovel' },
      { e: '🚕', k: 'taxi' },
      { e: '🚙', k: 'suv carro' },
      { e: '🚌', k: 'onibus' },
      { e: '🚎', k: 'trolebus onibus' },
      { e: '🏎️', k: 'carro de corrida formula 1' },
      { e: '🚓', k: 'viatura policia' },
      { e: '🚑', k: 'ambulancia' },
      { e: '🚒', k: 'bombeiro caminhao' },
      { e: '🚐', k: 'van' },
      { e: '🚚', k: 'caminhao entrega' },
      { e: '🚛', k: 'carreta caminhao' },
      { e: '🚜', k: 'trator' },
      { e: '🛵', k: 'moto scooter entrega' },
      { e: '🏍️', k: 'moto motocicleta' },
      { e: '🚲', k: 'bicicleta bike' },
      { e: '🛴', k: 'patinete' },
      { e: '🚉', k: 'estacao trem' },
      { e: '🚄', k: 'trem bala' },
      { e: '🚆', k: 'trem' },
      { e: '🚇', k: 'metro' },
      { e: '🚊', k: 'bonde vlt' },
      { e: '✈️', k: 'aviao voo viagem' },
      { e: '🛫', k: 'decolagem aviao' },
      { e: '🛬', k: 'pouso aviao' },
      { e: '🚁', k: 'helicoptero' },
      { e: '🚀', k: 'foguete lancamento decolar' },
      { e: '🛸', k: 'disco voador ovni' },
      { e: '⛵', k: 'veleiro barco' },
      { e: '🚤', k: 'lancha barco' },
      { e: '🛳️', k: 'navio cruzeiro' },
      { e: '⛴️', k: 'balsa ferry' },
      { e: '🚢', k: 'navio' },
      { e: '⚓', k: 'ancora' },
      { e: '⛽', k: 'posto gasolina combustivel' },
      { e: '🚦', k: 'semaforo transito' },
      { e: '🚧', k: 'obras construcao' },
      { e: '🗺️', k: 'mapa viagem' },
      { e: '🧭', k: 'bussola direcao' },
      { e: '🏔️', k: 'montanha neve' },
      { e: '⛰️', k: 'montanha' },
      { e: '🌋', k: 'vulcao' },
      { e: '🏕️', k: 'acampamento camping' },
      { e: '🏖️', k: 'praia guarda sol' },
      { e: '🏜️', k: 'deserto' },
      { e: '🏝️', k: 'ilha praia' },
      { e: '🏟️', k: 'estadio' },
      { e: '🏛️', k: 'monumento classico' },
      { e: '🏗️', k: 'construcao obra' },
      { e: '🏘️', k: 'casas bairro' },
      { e: '🏠', k: 'casa lar' },
      { e: '🏡', k: 'casa jardim' },
      { e: '🏢', k: 'escritorio predio empresa' },
      { e: '🏣', k: 'correios japao' },
      { e: '🏥', k: 'hospital' },
      { e: '🏦', k: 'banco' },
      { e: '🏨', k: 'hotel' },
      { e: '🏪', k: 'loja conveniencia' },
      { e: '🏫', k: 'escola' },
      { e: '🏭', k: 'fabrica industria' },
      { e: '🏬', k: 'shopping loja' },
      { e: '💒', k: 'casamento igreja' },
      { e: '⛪', k: 'igreja' },
      { e: '🕌', k: 'mesquita' },
      { e: '🕍', k: 'sinagoga' },
      { e: '🗽', k: 'estatua da liberdade nova york' },
      { e: '🗼', k: 'torre de toquio' },
      { e: '🏰', k: 'castelo' },
      { e: '🌁', k: 'neblina cidade' },
      { e: '🌃', k: 'cidade a noite' },
      { e: '🌆', k: 'cidade entardecer' },
      { e: '🌇', k: 'por do sol cidade' },
      { e: '🌉', k: 'ponte noite' },
      { e: '🎡', k: 'roda gigante parque' },
      { e: '🎢', k: 'montanha russa parque' },
      { e: '🎠', k: 'carrossel' },
      { e: '⛲', k: 'chafariz fonte' },
    ],
  },
  {
    id: 'objetos',
    label: 'Objetos',
    icon: '💡',
    items: [
      { e: '⌚', k: 'relogio pulso hora' },
      { e: '📱', k: 'celular telefone smartphone' },
      { e: '💻', k: 'notebook computador laptop' },
      { e: '🖥️', k: 'computador desktop monitor' },
      { e: '🖨️', k: 'impressora imprimir' },
      { e: '⌨️', k: 'teclado' },
      { e: '🖱️', k: 'mouse' },
      { e: '💽', k: 'disco midia' },
      { e: '💾', k: 'disquete salvar' },
      { e: '💿', k: 'cd disco' },
      { e: '📀', k: 'dvd disco' },
      { e: '📷', k: 'camera foto' },
      { e: '📸', k: 'camera flash foto' },
      { e: '📹', k: 'filmadora video' },
      { e: '🎥', k: 'camera cinema filme' },
      { e: '📽️', k: 'projetor filme' },
      { e: '📺', k: 'televisao tv' },
      { e: '📻', k: 'radio' },
      { e: '🎙️', k: 'microfone podcast estudio' },
      { e: '⏰', k: 'despertador alarme hora' },
      { e: '⏱️', k: 'cronometro tempo' },
      { e: '⏳', k: 'ampulheta tempo esperando' },
      { e: '📡', k: 'antena satelite sinal' },
      { e: '🔋', k: 'bateria energia' },
      { e: '🔌', k: 'tomada plugue energia' },
      { e: '💡', k: 'lampada ideia' },
      { e: '🔦', k: 'lanterna luz' },
      { e: '🕯️', k: 'vela' },
      { e: '🧯', k: 'extintor incendio' },
      { e: '🛢️', k: 'barril petroleo' },
      { e: '💸', k: 'dinheiro voando gasto' },
      { e: '💵', k: 'dinheiro nota dolar' },
      { e: '💰', k: 'saco de dinheiro grana lucro' },
      { e: '💳', k: 'cartao de credito pagamento' },
      { e: '🧾', k: 'recibo nota fiscal fatura' },
      { e: '💎', k: 'diamante joia' },
      { e: '⚖️', k: 'balanca justica equilibrio' },
      { e: '🔧', k: 'chave inglesa ferramenta conserto' },
      { e: '🔨', k: 'martelo ferramenta' },
      { e: '🛠️', k: 'ferramentas manutencao' },
      { e: '⚙️', k: 'engrenagem configuracao' },
      { e: '🔩', k: 'parafuso porca' },
      { e: '🧰', k: 'caixa de ferramentas' },
      { e: '🧲', k: 'ima atracao' },
      { e: '🔫', k: 'arma pistola' },
      { e: '💊', k: 'remedio comprimido' },
      { e: '💉', k: 'seringa vacina injecao' },
      { e: '🩺', k: 'estetoscopio medico' },
      { e: '🚪', k: 'porta' },
      { e: '🛏️', k: 'cama dormir' },
      { e: '🛋️', k: 'sofa sala' },
      { e: '🚽', k: 'vaso sanitario banheiro' },
      { e: '🚿', k: 'chuveiro banho' },
      { e: '🛁', k: 'banheira banho' },
      { e: '🧹', k: 'vassoura limpeza' },
      { e: '🧺', k: 'cesto roupa' },
      { e: '🧻', k: 'papel higienico' },
      { e: '🧼', k: 'sabonete limpeza' },
      { e: '🔑', k: 'chave acesso senha' },
      { e: '🔒', k: 'cadeado fechado seguranca' },
      { e: '🔓', k: 'cadeado aberto' },
      { e: '📦', k: 'caixa pacote entrega encomenda' },
      { e: '📫', k: 'caixa de correio' },
      { e: '📮', k: 'caixa postal correio' },
      { e: '✉️', k: 'envelope email carta' },
      { e: '📧', k: 'email arroba mensagem' },
      { e: '📨', k: 'email recebido mensagem' },
      { e: '📩', k: 'email enviado mensagem' },
      { e: '📝', k: 'anotacao escrever nota' },
      { e: '📄', k: 'documento folha arquivo' },
      { e: '📃', k: 'documento pagina' },
      { e: '📑', k: 'marcadores documentos' },
      { e: '📊', k: 'grafico barras relatorio dados' },
      { e: '📈', k: 'grafico subindo crescimento vendas' },
      { e: '📉', k: 'grafico caindo queda prejuizo' },
      { e: '📋', k: 'prancheta lista checklist' },
      { e: '📌', k: 'alfinete fixar' },
      { e: '📎', k: 'clipe anexo' },
      { e: '📁', k: 'pasta arquivo' },
      { e: '📂', k: 'pasta aberta arquivos' },
      { e: '🗂️', k: 'pastas organizacao' },
      { e: '📅', k: 'calendario data agenda' },
      { e: '📆', k: 'calendario agenda' },
      { e: '🗓️', k: 'calendario mes agenda' },
      { e: '📇', k: 'fichario contatos' },
      { e: '🗃️', k: 'arquivo caixa' },
      { e: '🗑️', k: 'lixeira excluir apagar' },
      { e: '📚', k: 'livros estudo' },
      { e: '📖', k: 'livro aberto leitura' },
      { e: '🔖', k: 'marcador de livro' },
      { e: '📰', k: 'jornal noticia' },
      { e: '✏️', k: 'lapis escrever' },
      { e: '✒️', k: 'caneta tinta' },
      { e: '🖊️', k: 'caneta escrever' },
      { e: '🖍️', k: 'giz de cera' },
      { e: '📏', k: 'regua medida' },
      { e: '📐', k: 'esquadro medida' },
      { e: '✂️', k: 'tesoura cortar' },
      { e: '🔍', k: 'lupa busca procurar pesquisa' },
      { e: '🔎', k: 'lupa busca pesquisa' },
      { e: '🔔', k: 'sino notificacao aviso' },
      { e: '🔕', k: 'sino cortado silencio mudo' },
      { e: '📢', k: 'megafone anuncio aviso' },
      { e: '📣', k: 'megafone torcida anuncio' },
      { e: '👑', k: 'coroa rei rainha' },
      { e: '👓', k: 'oculos' },
      { e: '🕶️', k: 'oculos escuros' },
      { e: '👔', k: 'gravata terno trabalho' },
      { e: '👕', k: 'camiseta roupa' },
      { e: '👗', k: 'vestido roupa' },
      { e: '👠', k: 'salto sapato' },
      { e: '👟', k: 'tenis sapato' },
      { e: '🎒', k: 'mochila escola' },
      { e: '💼', k: 'maleta trabalho negocio' },
      { e: '👜', k: 'bolsa' },
      { e: '☂️', k: 'guarda chuva' },
      { e: '🧳', k: 'mala viagem' },
    ],
  },
  {
    id: 'simbolos',
    label: 'Símbolos',
    icon: '❤️',
    items: [
      { e: '✅', k: 'certo confirmado ok verde check' },
      { e: '☑️', k: 'marcado check caixa' },
      { e: '✔️', k: 'certo check confirmado' },
      { e: '❌', k: 'errado x cancelar nao' },
      { e: '❎', k: 'x cancelar' },
      { e: '⭕', k: 'circulo certo' },
      { e: '🚫', k: 'proibido bloqueado' },
      { e: '⛔', k: 'proibido entrada' },
      { e: '‼️', k: 'exclamacao dupla urgente' },
      { e: '❗', k: 'exclamacao atencao importante' },
      { e: '❓', k: 'interrogacao duvida pergunta' },
      { e: '❔', k: 'interrogacao branca duvida' },
      { e: '⚠️', k: 'atencao aviso cuidado perigo' },
      { e: '🔞', k: 'proibido menores 18' },
      { e: '📵', k: 'proibido celular' },
      { e: '🔇', k: 'mudo sem som' },
      { e: '🔊', k: 'som alto volume' },
      { e: '💬', k: 'balao de fala mensagem conversa' },
      { e: '💭', k: 'balao de pensamento' },
      { e: '🗨️', k: 'balao fala' },
      { e: '🗯️', k: 'balao raiva' },
      { e: '♻️', k: 'reciclagem sustentavel' },
      { e: '⚜️', k: 'flor de lis' },
      { e: '🔱', k: 'tridente' },
      { e: '⚛️', k: 'atomo ciencia' },
      { e: '🕉️', k: 'om hindu' },
      { e: '✡️', k: 'estrela de davi' },
      { e: '☪️', k: 'islamismo' },
      { e: '☮️', k: 'paz' },
      { e: '✝️', k: 'cruz cristao' },
      { e: '☯️', k: 'yin yang equilibrio' },
      { e: '♈', k: 'aries signo' },
      { e: '♉', k: 'touro signo' },
      { e: '♊', k: 'gemeos signo' },
      { e: '♋', k: 'cancer signo' },
      { e: '♌', k: 'leao signo' },
      { e: '♍', k: 'virgem signo' },
      { e: '♎', k: 'libra signo' },
      { e: '♏', k: 'escorpiao signo' },
      { e: '♐', k: 'sagitario signo' },
      { e: '♑', k: 'capricornio signo' },
      { e: '♒', k: 'aquario signo' },
      { e: '♓', k: 'peixes signo' },
      { e: '🆔', k: 'identidade id' },
      { e: '🆕', k: 'novo new' },
      { e: '🆓', k: 'gratis free' },
      { e: '🆗', k: 'ok certo' },
      { e: '🆙', k: 'up cima' },
      { e: '🈵', k: 'lotado cheio' },
      { e: '🔴', k: 'circulo vermelho bolinha' },
      { e: '🟠', k: 'circulo laranja' },
      { e: '🟡', k: 'circulo amarelo' },
      { e: '🟢', k: 'circulo verde online' },
      { e: '🔵', k: 'circulo azul' },
      { e: '🟣', k: 'circulo roxo' },
      { e: '⚫', k: 'circulo preto' },
      { e: '⚪', k: 'circulo branco' },
      { e: '🟥', k: 'quadrado vermelho' },
      { e: '🟩', k: 'quadrado verde' },
      { e: '🟦', k: 'quadrado azul' },
      { e: '⬛', k: 'quadrado preto' },
      { e: '⬜', k: 'quadrado branco' },
      { e: '🔶', k: 'losango laranja' },
      { e: '🔷', k: 'losango azul' },
      { e: '🔺', k: 'triangulo vermelho cima' },
      { e: '🔻', k: 'triangulo vermelho baixo' },
      { e: '➡️', k: 'seta direita' },
      { e: '⬅️', k: 'seta esquerda' },
      { e: '⬆️', k: 'seta cima' },
      { e: '⬇️', k: 'seta baixo' },
      { e: '🔄', k: 'atualizar sincronizar repetir' },
      { e: '🔃', k: 'recarregar girar' },
      { e: '▶️', k: 'play tocar' },
      { e: '⏸️', k: 'pausa' },
      { e: '⏹️', k: 'parar stop' },
      { e: '⏺️', k: 'gravar rec' },
      { e: '⏭️', k: 'proxima avancar' },
      { e: '⏮️', k: 'anterior voltar' },
      { e: '🔀', k: 'aleatorio shuffle' },
      { e: '🔁', k: 'repetir loop' },
      { e: '➕', k: 'mais adicionar soma' },
      { e: '➖', k: 'menos subtrair' },
      { e: '✖️', k: 'vezes multiplicar' },
      { e: '➗', k: 'dividir divisao' },
      { e: '💲', k: 'cifrao dinheiro dolar' },
      { e: '™️', k: 'marca registrada' },
      { e: '©️', k: 'copyright direitos' },
      { e: '®️', k: 'marca registrada' },
      { e: '#️⃣', k: 'hashtag cerquilha' },
      { e: '*️⃣', k: 'asterisco' },
      { e: '0️⃣', k: 'zero numero' },
      { e: '1️⃣', k: 'um numero' },
      { e: '2️⃣', k: 'dois numero' },
      { e: '3️⃣', k: 'tres numero' },
      { e: '4️⃣', k: 'quatro numero' },
      { e: '5️⃣', k: 'cinco numero' },
      { e: '6️⃣', k: 'seis numero' },
      { e: '7️⃣', k: 'sete numero' },
      { e: '8️⃣', k: 'oito numero' },
      { e: '9️⃣', k: 'nove numero' },
      { e: '🔟', k: 'dez numero' },
    ],
  },
  {
    id: 'bandeiras',
    label: 'Bandeiras',
    icon: '🏳️',
    items: [
      { e: '🏳️', k: 'bandeira branca rendicao' },
      { e: '🏴', k: 'bandeira preta' },
      { e: '🏁', k: 'bandeira quadriculada chegada fim' },
      { e: '🚩', k: 'bandeira vermelha alerta' },
      { e: '🏳️‍🌈', k: 'bandeira arco iris lgbt orgulho' },
      { e: '🇧🇷', k: 'brasil bandeira' },
      { e: '🇵🇹', k: 'portugal bandeira' },
      { e: '🇺🇸', k: 'estados unidos eua bandeira' },
      { e: '🇦🇷', k: 'argentina bandeira' },
      { e: '🇺🇾', k: 'uruguai bandeira' },
      { e: '🇨🇱', k: 'chile bandeira' },
      { e: '🇵🇾', k: 'paraguai bandeira' },
      { e: '🇧🇴', k: 'bolivia bandeira' },
      { e: '🇨🇴', k: 'colombia bandeira' },
      { e: '🇵🇪', k: 'peru bandeira' },
      { e: '🇲🇽', k: 'mexico bandeira' },
      { e: '🇨🇦', k: 'canada bandeira' },
      { e: '🇪🇸', k: 'espanha bandeira' },
      { e: '🇫🇷', k: 'franca bandeira' },
      { e: '🇮🇹', k: 'italia bandeira' },
      { e: '🇩🇪', k: 'alemanha bandeira' },
      { e: '🇬🇧', k: 'reino unido inglaterra bandeira' },
      { e: '🇮🇪', k: 'irlanda bandeira' },
      { e: '🇳🇱', k: 'holanda paises baixos bandeira' },
      { e: '🇨🇭', k: 'suica bandeira' },
      { e: '🇸🇪', k: 'suecia bandeira' },
      { e: '🇳🇴', k: 'noruega bandeira' },
      { e: '🇷🇺', k: 'russia bandeira' },
      { e: '🇨🇳', k: 'china bandeira' },
      { e: '🇯🇵', k: 'japao bandeira' },
      { e: '🇰🇷', k: 'coreia do sul bandeira' },
      { e: '🇮🇳', k: 'india bandeira' },
      { e: '🇦🇺', k: 'australia bandeira' },
      { e: '🇿🇦', k: 'africa do sul bandeira' },
      { e: '🇦🇴', k: 'angola bandeira' },
      { e: '🇲🇿', k: 'mocambique bandeira' },
    ],
  },
]

/** Sem acento e em minúsculas — usado nos dois lados da busca. */
function fold(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

/** Índice de busca montado uma vez: emoji + palavras-chave já normalizadas. */
const SEARCH_INDEX: { item: EmojiEntry; hay: string }[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.items.map((item) => ({ item, hay: fold(`${c.label} ${item.k}`) })),
)

/** Busca por palavra-chave (acento-insensível). Query vazia devolve lista vazia. */
export function searchEmojis(query: string, limit = 120): EmojiEntry[] {
  const q = fold(query.trim())
  if (!q) return []
  const terms = q.split(/\s+/)
  const out: EmojiEntry[] = []
  for (const { item, hay } of SEARCH_INDEX) {
    if (terms.every((t) => hay.includes(t))) out.push(item)
    if (out.length >= limit) break
  }
  return out
}

/** Todos os emojis do catálogo, indexados pelo caractere — resolve os "frequentes" salvos. */
const BY_CHAR = new Map(EMOJI_CATEGORIES.flatMap((c) => c.items).map((i) => [i.e, i]))

export function emojiByChar(char: string): EmojiEntry | undefined {
  return BY_CHAR.get(char)
}
